// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderBuyerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IdCard        string                 `protobuf:"bytes,3,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBuyerInfo) Reset() {
	*x = OrderBuyerInfo{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBuyerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBuyerInfo) ProtoMessage() {}

func (x *OrderBuyerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBuyerInfo.ProtoReflect.Descriptor instead.
func (*OrderBuyerInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderBuyerInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderBuyerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderBuyerInfo) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *OrderBuyerInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type OrderTicketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketBuyerId int64                  `protobuf:"varint,2,opt,name=ticket_buyer_id,json=ticketBuyerId,proto3" json:"ticket_buyer_id,omitempty"`
	TicketCode    string                 `protobuf:"bytes,3,opt,name=ticket_code,json=ticketCode,proto3" json:"ticket_code,omitempty"`
	QrCodeUrl     string                 `protobuf:"bytes,4,opt,name=qr_code_url,json=qrCodeUrl,proto3" json:"qr_code_url,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	SeatInfo      string                 `protobuf:"bytes,6,opt,name=seat_info,json=seatInfo,proto3" json:"seat_info,omitempty"`
	VerifiedAt    string                 `protobuf:"bytes,7,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	Buyer         *OrderBuyerInfo        `protobuf:"bytes,8,opt,name=buyer,proto3" json:"buyer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTicketInfo) Reset() {
	*x = OrderTicketInfo{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTicketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTicketInfo) ProtoMessage() {}

func (x *OrderTicketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTicketInfo.ProtoReflect.Descriptor instead.
func (*OrderTicketInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderTicketInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderTicketInfo) GetTicketBuyerId() int64 {
	if x != nil {
		return x.TicketBuyerId
	}
	return 0
}

func (x *OrderTicketInfo) GetTicketCode() string {
	if x != nil {
		return x.TicketCode
	}
	return ""
}

func (x *OrderTicketInfo) GetQrCodeUrl() string {
	if x != nil {
		return x.QrCodeUrl
	}
	return ""
}

func (x *OrderTicketInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderTicketInfo) GetSeatInfo() string {
	if x != nil {
		return x.SeatInfo
	}
	return ""
}

func (x *OrderTicketInfo) GetVerifiedAt() string {
	if x != nil {
		return x.VerifiedAt
	}
	return ""
}

func (x *OrderTicketInfo) GetBuyer() *OrderBuyerInfo {
	if x != nil {
		return x.Buyer
	}
	return nil
}

type OrderPaymentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentNo     string                 `protobuf:"bytes,2,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	PayMethod     int32                  `protobuf:"varint,3,opt,name=pay_method,json=payMethod,proto3" json:"pay_method,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	TradeNo       string                 `protobuf:"bytes,6,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	PaidAt        string                 `protobuf:"bytes,7,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CallbackData  string                 `protobuf:"bytes,9,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPaymentInfo) Reset() {
	*x = OrderPaymentInfo{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaymentInfo) ProtoMessage() {}

func (x *OrderPaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaymentInfo.ProtoReflect.Descriptor instead.
func (*OrderPaymentInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderPaymentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderPaymentInfo) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *OrderPaymentInfo) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

func (x *OrderPaymentInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderPaymentInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderPaymentInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *OrderPaymentInfo) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *OrderPaymentInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderPaymentInfo) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

type OrderRefundInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RefundNo      string                 `protobuf:"bytes,2,opt,name=refund_no,json=refundNo,proto3" json:"refund_no,omitempty"`
	RefundAmount  float64                `protobuf:"fixed64,3,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	RejectReason  string                 `protobuf:"bytes,6,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	TradeNo       string                 `protobuf:"bytes,7,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RefundedAt    string                 `protobuf:"bytes,9,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRefundInfo) Reset() {
	*x = OrderRefundInfo{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRefundInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRefundInfo) ProtoMessage() {}

func (x *OrderRefundInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRefundInfo.ProtoReflect.Descriptor instead.
func (*OrderRefundInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderRefundInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderRefundInfo) GetRefundNo() string {
	if x != nil {
		return x.RefundNo
	}
	return ""
}

func (x *OrderRefundInfo) GetRefundAmount() float64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *OrderRefundInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderRefundInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderRefundInfo) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *OrderRefundInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *OrderRefundInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderRefundInfo) GetRefundedAt() string {
	if x != nil {
		return x.RefundedAt
	}
	return ""
}

type OrderDeliveryInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TicketType     int32                  `protobuf:"varint,1,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	DeliveryMethod string                 `protobuf:"bytes,2,opt,name=delivery_method,json=deliveryMethod,proto3" json:"delivery_method,omitempty"`
	AddressId      int64                  `protobuf:"varint,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	ReceiverName   string                 `protobuf:"bytes,4,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone  string                 `protobuf:"bytes,5,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	Province       string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	City           string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	District       string                 `protobuf:"bytes,8,opt,name=district,proto3" json:"district,omitempty"`
	Detail         string                 `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`
	DeliveryStatus string                 `protobuf:"bytes,10,opt,name=delivery_status,json=deliveryStatus,proto3" json:"delivery_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderDeliveryInfo) Reset() {
	*x = OrderDeliveryInfo{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeliveryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeliveryInfo) ProtoMessage() {}

func (x *OrderDeliveryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeliveryInfo.ProtoReflect.Descriptor instead.
func (*OrderDeliveryInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderDeliveryInfo) GetTicketType() int32 {
	if x != nil {
		return x.TicketType
	}
	return 0
}

func (x *OrderDeliveryInfo) GetDeliveryMethod() string {
	if x != nil {
		return x.DeliveryMethod
	}
	return ""
}

func (x *OrderDeliveryInfo) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *OrderDeliveryInfo) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *OrderDeliveryInfo) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *OrderDeliveryInfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *OrderDeliveryInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OrderDeliveryInfo) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *OrderDeliveryInfo) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *OrderDeliveryInfo) GetDeliveryStatus() string {
	if x != nil {
		return x.DeliveryStatus
	}
	return ""
}

type OrderSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo        string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	EventId        int64                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TicketTierId   int64                  `protobuf:"varint,4,opt,name=ticket_tier_id,json=ticketTierId,proto3" json:"ticket_tier_id,omitempty"`
	EventTitle     string                 `protobuf:"bytes,5,opt,name=event_title,json=eventTitle,proto3" json:"event_title,omitempty"`
	PosterUrl      string                 `protobuf:"bytes,6,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	VenueName      string                 `protobuf:"bytes,7,opt,name=venue_name,json=venueName,proto3" json:"venue_name,omitempty"`
	City           string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	EventStartTime string                 `protobuf:"bytes,9,opt,name=event_start_time,json=eventStartTime,proto3" json:"event_start_time,omitempty"`
	EventEndTime   string                 `protobuf:"bytes,10,opt,name=event_end_time,json=eventEndTime,proto3" json:"event_end_time,omitempty"`
	TicketTierName string                 `protobuf:"bytes,11,opt,name=ticket_tier_name,json=ticketTierName,proto3" json:"ticket_tier_name,omitempty"`
	Quantity       int32                  `protobuf:"varint,12,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice      float64                `protobuf:"fixed64,13,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalAmount    float64                `protobuf:"fixed64,14,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status         int32                  `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	StatusText     string                 `protobuf:"bytes,16,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	PayDeadline    string                 `protobuf:"bytes,17,opt,name=pay_deadline,json=payDeadline,proto3" json:"pay_deadline,omitempty"`
	PaidAt         string                 `protobuf:"bytes,18,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CancelledAt    string                 `protobuf:"bytes,19,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TicketType     int32                  `protobuf:"varint,21,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderSummary) Reset() {
	*x = OrderSummary{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSummary) ProtoMessage() {}

func (x *OrderSummary) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSummary.ProtoReflect.Descriptor instead.
func (*OrderSummary) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderSummary) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderSummary) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *OrderSummary) GetTicketTierId() int64 {
	if x != nil {
		return x.TicketTierId
	}
	return 0
}

func (x *OrderSummary) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

func (x *OrderSummary) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *OrderSummary) GetVenueName() string {
	if x != nil {
		return x.VenueName
	}
	return ""
}

func (x *OrderSummary) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OrderSummary) GetEventStartTime() string {
	if x != nil {
		return x.EventStartTime
	}
	return ""
}

func (x *OrderSummary) GetEventEndTime() string {
	if x != nil {
		return x.EventEndTime
	}
	return ""
}

func (x *OrderSummary) GetTicketTierName() string {
	if x != nil {
		return x.TicketTierName
	}
	return ""
}

func (x *OrderSummary) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderSummary) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderSummary) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderSummary) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderSummary) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *OrderSummary) GetPayDeadline() string {
	if x != nil {
		return x.PayDeadline
	}
	return ""
}

func (x *OrderSummary) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *OrderSummary) GetCancelledAt() string {
	if x != nil {
		return x.CancelledAt
	}
	return ""
}

func (x *OrderSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderSummary) GetTicketType() int32 {
	if x != nil {
		return x.TicketType
	}
	return 0
}

type OrderDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo        string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId         int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId        int64                  `protobuf:"varint,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TicketTierId   int64                  `protobuf:"varint,5,opt,name=ticket_tier_id,json=ticketTierId,proto3" json:"ticket_tier_id,omitempty"`
	EventTitle     string                 `protobuf:"bytes,6,opt,name=event_title,json=eventTitle,proto3" json:"event_title,omitempty"`
	Description    string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	PosterUrl      string                 `protobuf:"bytes,8,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	VenueName      string                 `protobuf:"bytes,9,opt,name=venue_name,json=venueName,proto3" json:"venue_name,omitempty"`
	VenueAddress   string                 `protobuf:"bytes,10,opt,name=venue_address,json=venueAddress,proto3" json:"venue_address,omitempty"`
	City           string                 `protobuf:"bytes,11,opt,name=city,proto3" json:"city,omitempty"`
	EventStartTime string                 `protobuf:"bytes,12,opt,name=event_start_time,json=eventStartTime,proto3" json:"event_start_time,omitempty"`
	EventEndTime   string                 `protobuf:"bytes,13,opt,name=event_end_time,json=eventEndTime,proto3" json:"event_end_time,omitempty"`
	SaleStartTime  string                 `protobuf:"bytes,14,opt,name=sale_start_time,json=saleStartTime,proto3" json:"sale_start_time,omitempty"`
	SaleEndTime    string                 `protobuf:"bytes,15,opt,name=sale_end_time,json=saleEndTime,proto3" json:"sale_end_time,omitempty"`
	TicketTierName string                 `protobuf:"bytes,16,opt,name=ticket_tier_name,json=ticketTierName,proto3" json:"ticket_tier_name,omitempty"`
	Quantity       int32                  `protobuf:"varint,17,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice      float64                `protobuf:"fixed64,18,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalAmount    float64                `protobuf:"fixed64,19,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status         int32                  `protobuf:"varint,20,opt,name=status,proto3" json:"status,omitempty"`
	StatusText     string                 `protobuf:"bytes,21,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	PayDeadline    string                 `protobuf:"bytes,22,opt,name=pay_deadline,json=payDeadline,proto3" json:"pay_deadline,omitempty"`
	PaidAt         string                 `protobuf:"bytes,23,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CancelledAt    string                 `protobuf:"bytes,24,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,25,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PurchaseLimit  int32                  `protobuf:"varint,26,opt,name=purchase_limit,json=purchaseLimit,proto3" json:"purchase_limit,omitempty"`
	NeedRealName   int32                  `protobuf:"varint,27,opt,name=need_real_name,json=needRealName,proto3" json:"need_real_name,omitempty"`
	TicketType     int32                  `protobuf:"varint,28,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	Delivery       *OrderDeliveryInfo     `protobuf:"bytes,29,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Tickets        []*OrderTicketInfo     `protobuf:"bytes,30,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Payment        *OrderPaymentInfo      `protobuf:"bytes,31,opt,name=payment,proto3" json:"payment,omitempty"`
	Refund         *OrderRefundInfo       `protobuf:"bytes,32,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderDetail) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderDetail) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderDetail) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *OrderDetail) GetTicketTierId() int64 {
	if x != nil {
		return x.TicketTierId
	}
	return 0
}

func (x *OrderDetail) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

func (x *OrderDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrderDetail) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *OrderDetail) GetVenueName() string {
	if x != nil {
		return x.VenueName
	}
	return ""
}

func (x *OrderDetail) GetVenueAddress() string {
	if x != nil {
		return x.VenueAddress
	}
	return ""
}

func (x *OrderDetail) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OrderDetail) GetEventStartTime() string {
	if x != nil {
		return x.EventStartTime
	}
	return ""
}

func (x *OrderDetail) GetEventEndTime() string {
	if x != nil {
		return x.EventEndTime
	}
	return ""
}

func (x *OrderDetail) GetSaleStartTime() string {
	if x != nil {
		return x.SaleStartTime
	}
	return ""
}

func (x *OrderDetail) GetSaleEndTime() string {
	if x != nil {
		return x.SaleEndTime
	}
	return ""
}

func (x *OrderDetail) GetTicketTierName() string {
	if x != nil {
		return x.TicketTierName
	}
	return ""
}

func (x *OrderDetail) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderDetail) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderDetail) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderDetail) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *OrderDetail) GetPayDeadline() string {
	if x != nil {
		return x.PayDeadline
	}
	return ""
}

func (x *OrderDetail) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *OrderDetail) GetCancelledAt() string {
	if x != nil {
		return x.CancelledAt
	}
	return ""
}

func (x *OrderDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderDetail) GetPurchaseLimit() int32 {
	if x != nil {
		return x.PurchaseLimit
	}
	return 0
}

func (x *OrderDetail) GetNeedRealName() int32 {
	if x != nil {
		return x.NeedRealName
	}
	return 0
}

func (x *OrderDetail) GetTicketType() int32 {
	if x != nil {
		return x.TicketType
	}
	return 0
}

func (x *OrderDetail) GetDelivery() *OrderDeliveryInfo {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *OrderDetail) GetTickets() []*OrderTicketInfo {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *OrderDetail) GetPayment() *OrderPaymentInfo {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *OrderDetail) GetRefund() *OrderRefundInfo {
	if x != nil {
		return x.Refund
	}
	return nil
}

type CreateOrderReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId        int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TicketTierId   int64                  `protobuf:"varint,3,opt,name=ticket_tier_id,json=ticketTierId,proto3" json:"ticket_tier_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TicketBuyerIds []int64                `protobuf:"varint,5,rep,packed,name=ticket_buyer_ids,json=ticketBuyerIds,proto3" json:"ticket_buyer_ids,omitempty"`
	AddressId      int64                  `protobuf:"varint,6,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	PayMethod      int32                  `protobuf:"varint,7,opt,name=pay_method,json=payMethod,proto3" json:"pay_method,omitempty"`
	RequestId      string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateOrderReq) GetTicketTierId() int64 {
	if x != nil {
		return x.TicketTierId
	}
	return 0
}

func (x *CreateOrderReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderReq) GetTicketBuyerIds() []int64 {
	if x != nil {
		return x.TicketBuyerIds
	}
	return nil
}

func (x *CreateOrderReq) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *CreateOrderReq) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

func (x *CreateOrderReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	QueueToken    string                 `protobuf:"bytes,2,opt,name=queue_token,json=queueToken,proto3" json:"queue_token,omitempty"`
	QueueStatus   int32                  `protobuf:"varint,3,opt,name=queue_status,json=queueStatus,proto3" json:"queue_status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOrderResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateOrderResp) GetQueueToken() string {
	if x != nil {
		return x.QueueToken
	}
	return ""
}

func (x *CreateOrderResp) GetQueueStatus() int32 {
	if x != nil {
		return x.QueueStatus
	}
	return 0
}

func (x *CreateOrderResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetQueueStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QueueToken    string                 `protobuf:"bytes,2,opt,name=queue_token,json=queueToken,proto3" json:"queue_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatusReq) Reset() {
	*x = GetQueueStatusReq{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatusReq) ProtoMessage() {}

func (x *GetQueueStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatusReq.ProtoReflect.Descriptor instead.
func (*GetQueueStatusReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetQueueStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetQueueStatusReq) GetQueueToken() string {
	if x != nil {
		return x.QueueToken
	}
	return ""
}

type GetQueueStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueToken    string                 `protobuf:"bytes,1,opt,name=queue_token,json=queueToken,proto3" json:"queue_token,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	QueueStatus   int32                  `protobuf:"varint,3,opt,name=queue_status,json=queueStatus,proto3" json:"queue_status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Order         *OrderSummary          `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatusResp) Reset() {
	*x = GetQueueStatusResp{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatusResp) ProtoMessage() {}

func (x *GetQueueStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatusResp.ProtoReflect.Descriptor instead.
func (*GetQueueStatusResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *GetQueueStatusResp) GetQueueToken() string {
	if x != nil {
		return x.QueueToken
	}
	return ""
}

func (x *GetQueueStatusResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetQueueStatusResp) GetQueueStatus() int32 {
	if x != nil {
		return x.QueueStatus
	}
	return 0
}

func (x *GetQueueStatusResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetQueueStatusResp) GetOrder() *OrderSummary {
	if x != nil {
		return x.Order
	}
	return nil
}

type PayOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PayMethod     int32                  `protobuf:"varint,3,opt,name=pay_method,json=payMethod,proto3" json:"pay_method,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderReq) Reset() {
	*x = PayOrderReq{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderReq) ProtoMessage() {}

func (x *PayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderReq.ProtoReflect.Descriptor instead.
func (*PayOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *PayOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PayOrderReq) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

func (x *PayOrderReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type PayOrderResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PayForm           string                 `protobuf:"bytes,2,opt,name=pay_form,json=payForm,proto3" json:"pay_form,omitempty"`
	Payment           *OrderPaymentInfo      `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	OrderStatus       int32                  `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaidAt            string                 `protobuf:"bytes,5,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CheckoutUrl       string                 `protobuf:"bytes,6,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	CheckoutSessionId string                 `protobuf:"bytes,7,opt,name=checkout_session_id,json=checkoutSessionId,proto3" json:"checkout_session_id,omitempty"`
	SessionExpiresAt  string                 `protobuf:"bytes,8,opt,name=session_expires_at,json=sessionExpiresAt,proto3" json:"session_expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PayOrderResp) Reset() {
	*x = PayOrderResp{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderResp) ProtoMessage() {}

func (x *PayOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderResp.ProtoReflect.Descriptor instead.
func (*PayOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *PayOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PayOrderResp) GetPayForm() string {
	if x != nil {
		return x.PayForm
	}
	return ""
}

func (x *PayOrderResp) GetPayment() *OrderPaymentInfo {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *PayOrderResp) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *PayOrderResp) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *PayOrderResp) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *PayOrderResp) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

func (x *PayOrderResp) GetSessionExpiresAt() string {
	if x != nil {
		return x.SessionExpiresAt
	}
	return ""
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *CancelOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type CancelOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResp) Reset() {
	*x = CancelOrderResp{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResp) ProtoMessage() {}

func (x *CancelOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResp.ProtoReflect.Descriptor instead.
func (*CancelOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *CancelOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type ApplyRefundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRefundReq) Reset() {
	*x = ApplyRefundReq{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRefundReq) ProtoMessage() {}

func (x *ApplyRefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRefundReq.ProtoReflect.Descriptor instead.
func (*ApplyRefundReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *ApplyRefundReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApplyRefundReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ApplyRefundReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ApplyRefundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Refund        *OrderRefundInfo       `protobuf:"bytes,3,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRefundResp) Reset() {
	*x = ApplyRefundResp{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRefundResp) ProtoMessage() {}

func (x *ApplyRefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRefundResp.ProtoReflect.Descriptor instead.
func (*ApplyRefundResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *ApplyRefundResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyRefundResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ApplyRefundResp) GetRefund() *OrderRefundInfo {
	if x != nil {
		return x.Refund
	}
	return nil
}

type ListOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReq) Reset() {
	*x = ListOrderReq{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReq) ProtoMessage() {}

func (x *ListOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReq.ProtoReflect.Descriptor instead.
func (*ListOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *ListOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrderReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListOrderReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrderReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderSummary        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderResp) Reset() {
	*x = ListOrderResp{}
	mi := &file_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderResp) ProtoMessage() {}

func (x *ListOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderResp.ProtoReflect.Descriptor instead.
func (*ListOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{18}
}

func (x *ListOrderResp) GetOrders() []*OrderSummary {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrderResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrderResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrderResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetOrderDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailReq) Reset() {
	*x = GetOrderDetailReq{}
	mi := &file_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailReq) ProtoMessage() {}

func (x *GetOrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailReq.ProtoReflect.Descriptor instead.
func (*GetOrderDetailReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{19}
}

func (x *GetOrderDetailReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderDetailReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetOrderDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderDetail           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailResp) Reset() {
	*x = GetOrderDetailResp{}
	mi := &file_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailResp) ProtoMessage() {}

func (x *GetOrderDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailResp.ProtoReflect.Descriptor instead.
func (*GetOrderDetailResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{20}
}

func (x *GetOrderDetailResp) GetOrder() *OrderDetail {
	if x != nil {
		return x.Order
	}
	return nil
}

type InventoryPreheatResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TicketTierId  int64                  `protobuf:"varint,2,opt,name=ticket_tier_id,json=ticketTierId,proto3" json:"ticket_tier_id,omitempty"`
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryPreheatResult) Reset() {
	*x = InventoryPreheatResult{}
	mi := &file_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryPreheatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryPreheatResult) ProtoMessage() {}

func (x *InventoryPreheatResult) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryPreheatResult.ProtoReflect.Descriptor instead.
func (*InventoryPreheatResult) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{21}
}

func (x *InventoryPreheatResult) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *InventoryPreheatResult) GetTicketTierId() int64 {
	if x != nil {
		return x.TicketTierId
	}
	return 0
}

func (x *InventoryPreheatResult) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *InventoryPreheatResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InventoryPreheatResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PreheatInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventIds      []int64                `protobuf:"varint,1,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreheatInventoryReq) Reset() {
	*x = PreheatInventoryReq{}
	mi := &file_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreheatInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreheatInventoryReq) ProtoMessage() {}

func (x *PreheatInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreheatInventoryReq.ProtoReflect.Descriptor instead.
func (*PreheatInventoryReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{22}
}

func (x *PreheatInventoryReq) GetEventIds() []int64 {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *PreheatInventoryReq) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type PreheatInventoryResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       []*InventoryPreheatResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreheatInventoryResp) Reset() {
	*x = PreheatInventoryResp{}
	mi := &file_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreheatInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreheatInventoryResp) ProtoMessage() {}

func (x *PreheatInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreheatInventoryResp.ProtoReflect.Descriptor instead.
func (*PreheatInventoryResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{23}
}

func (x *PreheatInventoryResp) GetResults() []*InventoryPreheatResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"c\n" +
	"\x0eOrderBuyerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aid_card\x18\x03 \x01(\tR\x06idCard\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"\x8d\x02\n" +
	"\x0fOrderTicketInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0fticket_buyer_id\x18\x02 \x01(\x03R\rticketBuyerId\x12\x1f\n" +
	"\vticket_code\x18\x03 \x01(\tR\n" +
	"ticketCode\x12\x1e\n" +
	"\vqr_code_url\x18\x04 \x01(\tR\tqrCodeUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1b\n" +
	"\tseat_info\x18\x06 \x01(\tR\bseatInfo\x12\x1f\n" +
	"\vverified_at\x18\a \x01(\tR\n" +
	"verifiedAt\x12+\n" +
	"\x05buyer\x18\b \x01(\v2\x15.order.OrderBuyerInfoR\x05buyer\"\x88\x02\n" +
	"\x10OrderPaymentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x02 \x01(\tR\tpaymentNo\x12\x1d\n" +
	"\n" +
	"pay_method\x18\x03 \x01(\x05R\tpayMethod\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x19\n" +
	"\btrade_no\x18\x06 \x01(\tR\atradeNo\x12\x17\n" +
	"\apaid_at\x18\a \x01(\tR\x06paidAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12#\n" +
	"\rcallback_data\x18\t \x01(\tR\fcallbackData\"\x93\x02\n" +
	"\x0fOrderRefundInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\trefund_no\x18\x02 \x01(\tR\brefundNo\x12#\n" +
	"\rrefund_amount\x18\x03 \x01(\x01R\frefundAmount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12#\n" +
	"\rreject_reason\x18\x06 \x01(\tR\frejectReason\x12\x19\n" +
	"\btrade_no\x18\a \x01(\tR\atradeNo\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vrefunded_at\x18\t \x01(\tR\n" +
	"refundedAt\"\xd5\x02\n" +
	"\x11OrderDeliveryInfo\x12\x1f\n" +
	"\vticket_type\x18\x01 \x01(\x05R\n" +
	"ticketType\x12'\n" +
	"\x0fdelivery_method\x18\x02 \x01(\tR\x0edeliveryMethod\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\x03R\taddressId\x12#\n" +
	"\rreceiver_name\x18\x04 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x05 \x01(\tR\rreceiverPhone\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\b \x01(\tR\bdistrict\x12\x16\n" +
	"\x06detail\x18\t \x01(\tR\x06detail\x12'\n" +
	"\x0fdelivery_status\x18\n" +
	" \x01(\tR\x0edeliveryStatus\"\x9d\x05\n" +
	"\fOrderSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\x12$\n" +
	"\x0eticket_tier_id\x18\x04 \x01(\x03R\fticketTierId\x12\x1f\n" +
	"\vevent_title\x18\x05 \x01(\tR\n" +
	"eventTitle\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x06 \x01(\tR\tposterUrl\x12\x1d\n" +
	"\n" +
	"venue_name\x18\a \x01(\tR\tvenueName\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12(\n" +
	"\x10event_start_time\x18\t \x01(\tR\x0eeventStartTime\x12$\n" +
	"\x0eevent_end_time\x18\n" +
	" \x01(\tR\feventEndTime\x12(\n" +
	"\x10ticket_tier_name\x18\v \x01(\tR\x0eticketTierName\x12\x1a\n" +
	"\bquantity\x18\f \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\r \x01(\x01R\tunitPrice\x12!\n" +
	"\ftotal_amount\x18\x0e \x01(\x01R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x10 \x01(\tR\n" +
	"statusText\x12!\n" +
	"\fpay_deadline\x18\x11 \x01(\tR\vpayDeadline\x12\x17\n" +
	"\apaid_at\x18\x12 \x01(\tR\x06paidAt\x12!\n" +
	"\fcancelled_at\x18\x13 \x01(\tR\vcancelledAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vticket_type\x18\x15 \x01(\x05R\n" +
	"ticketType\"\xe0\b\n" +
	"\vOrderDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\x03R\aeventId\x12$\n" +
	"\x0eticket_tier_id\x18\x05 \x01(\x03R\fticketTierId\x12\x1f\n" +
	"\vevent_title\x18\x06 \x01(\tR\n" +
	"eventTitle\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"poster_url\x18\b \x01(\tR\tposterUrl\x12\x1d\n" +
	"\n" +
	"venue_name\x18\t \x01(\tR\tvenueName\x12#\n" +
	"\rvenue_address\x18\n" +
	" \x01(\tR\fvenueAddress\x12\x12\n" +
	"\x04city\x18\v \x01(\tR\x04city\x12(\n" +
	"\x10event_start_time\x18\f \x01(\tR\x0eeventStartTime\x12$\n" +
	"\x0eevent_end_time\x18\r \x01(\tR\feventEndTime\x12&\n" +
	"\x0fsale_start_time\x18\x0e \x01(\tR\rsaleStartTime\x12\"\n" +
	"\rsale_end_time\x18\x0f \x01(\tR\vsaleEndTime\x12(\n" +
	"\x10ticket_tier_name\x18\x10 \x01(\tR\x0eticketTierName\x12\x1a\n" +
	"\bquantity\x18\x11 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x12 \x01(\x01R\tunitPrice\x12!\n" +
	"\ftotal_amount\x18\x13 \x01(\x01R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x14 \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x15 \x01(\tR\n" +
	"statusText\x12!\n" +
	"\fpay_deadline\x18\x16 \x01(\tR\vpayDeadline\x12\x17\n" +
	"\apaid_at\x18\x17 \x01(\tR\x06paidAt\x12!\n" +
	"\fcancelled_at\x18\x18 \x01(\tR\vcancelledAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x19 \x01(\tR\tcreatedAt\x12%\n" +
	"\x0epurchase_limit\x18\x1a \x01(\x05R\rpurchaseLimit\x12$\n" +
	"\x0eneed_real_name\x18\x1b \x01(\x05R\fneedRealName\x12\x1f\n" +
	"\vticket_type\x18\x1c \x01(\x05R\n" +
	"ticketType\x124\n" +
	"\bdelivery\x18\x1d \x01(\v2\x18.order.OrderDeliveryInfoR\bdelivery\x120\n" +
	"\atickets\x18\x1e \x03(\v2\x16.order.OrderTicketInfoR\atickets\x121\n" +
	"\apayment\x18\x1f \x01(\v2\x17.order.OrderPaymentInfoR\apayment\x12.\n" +
	"\x06refund\x18  \x01(\v2\x16.order.OrderRefundInfoR\x06refund\"\x8d\x02\n" +
	"\x0eCreateOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12$\n" +
	"\x0eticket_tier_id\x18\x03 \x01(\x03R\fticketTierId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12(\n" +
	"\x10ticket_buyer_ids\x18\x05 \x03(\x03R\x0eticketBuyerIds\x12\x1d\n" +
	"\n" +
	"address_id\x18\x06 \x01(\x03R\taddressId\x12\x1d\n" +
	"\n" +
	"pay_method\x18\a \x01(\x05R\tpayMethod\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\"\x8a\x01\n" +
	"\x0fCreateOrderResp\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vqueue_token\x18\x02 \x01(\tR\n" +
	"queueToken\x12!\n" +
	"\fqueue_status\x18\x03 \x01(\x05R\vqueueStatus\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"M\n" +
	"\x11GetQueueStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vqueue_token\x18\x02 \x01(\tR\n" +
	"queueToken\"\xb8\x01\n" +
	"\x12GetQueueStatusResp\x12\x1f\n" +
	"\vqueue_token\x18\x01 \x01(\tR\n" +
	"queueToken\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12!\n" +
	"\fqueue_status\x18\x03 \x01(\x05R\vqueueStatus\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12)\n" +
	"\x05order\x18\x05 \x01(\v2\x13.order.OrderSummaryR\x05order\"z\n" +
	"\vPayOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"pay_method\x18\x03 \x01(\x05R\tpayMethod\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\"\xb3\x02\n" +
	"\fPayOrderResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bpay_form\x18\x02 \x01(\tR\apayForm\x121\n" +
	"\apayment\x18\x03 \x01(\v2\x17.order.OrderPaymentInfoR\apayment\x12!\n" +
	"\forder_status\x18\x04 \x01(\x05R\vorderStatus\x12\x17\n" +
	"\apaid_at\x18\x05 \x01(\tR\x06paidAt\x12!\n" +
	"\fcheckout_url\x18\x06 \x01(\tR\vcheckoutUrl\x12.\n" +
	"\x13checkout_session_id\x18\a \x01(\tR\x11checkoutSessionId\x12,\n" +
	"\x12session_expires_at\x18\b \x01(\tR\x10sessionExpiresAt\"D\n" +
	"\x0eCancelOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"F\n" +
	"\x0fCancelOrderResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"\\\n" +
	"\x0eApplyRefundReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"v\n" +
	"\x0fApplyRefundResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12.\n" +
	"\x06refund\x18\x03 \x01(\v2\x16.order.OrderRefundInfoR\x06refund\"p\n" +
	"\fListOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x83\x01\n" +
	"\rListOrderResp\x12+\n" +
	"\x06orders\x18\x01 \x03(\v2\x13.order.OrderSummaryR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"G\n" +
	"\x11GetOrderDetailReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\">\n" +
	"\x12GetOrderDetailResp\x12(\n" +
	"\x05order\x18\x01 \x01(\v2\x12.order.OrderDetailR\x05order\"\xa3\x01\n" +
	"\x16InventoryPreheatResult\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12$\n" +
	"\x0eticket_tier_id\x18\x02 \x01(\x03R\fticketTierId\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"H\n" +
	"\x13PreheatInventoryReq\x12\x1b\n" +
	"\tevent_ids\x18\x01 \x03(\x03R\beventIds\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"O\n" +
	"\x14PreheatInventoryResp\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.order.InventoryPreheatResultR\aresults2\x90\x04\n" +
	"\fOrderService\x12K\n" +
	"\x10PreheatInventory\x12\x1a.order.PreheatInventoryReq\x1a\x1b.order.PreheatInventoryResp\x12<\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x16.order.CreateOrderResp\x12E\n" +
	"\x0eGetQueueStatus\x12\x18.order.GetQueueStatusReq\x1a\x19.order.GetQueueStatusResp\x123\n" +
	"\bPayOrder\x12\x12.order.PayOrderReq\x1a\x13.order.PayOrderResp\x12<\n" +
	"\vCancelOrder\x12\x15.order.CancelOrderReq\x1a\x16.order.CancelOrderResp\x12<\n" +
	"\vApplyRefund\x12\x15.order.ApplyRefundReq\x1a\x16.order.ApplyRefundResp\x126\n" +
	"\tListOrder\x12\x13.order.ListOrderReq\x1a\x14.order.ListOrderResp\x12E\n" +
	"\x0eGetOrderDetail\x12\x18.order.GetOrderDetailReq\x1a\x19.order.GetOrderDetailRespB\vZ\t./orderpbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_order_proto_goTypes = []any{
	(*OrderBuyerInfo)(nil),         // 0: order.OrderBuyerInfo
	(*OrderTicketInfo)(nil),        // 1: order.OrderTicketInfo
	(*OrderPaymentInfo)(nil),       // 2: order.OrderPaymentInfo
	(*OrderRefundInfo)(nil),        // 3: order.OrderRefundInfo
	(*OrderDeliveryInfo)(nil),      // 4: order.OrderDeliveryInfo
	(*OrderSummary)(nil),           // 5: order.OrderSummary
	(*OrderDetail)(nil),            // 6: order.OrderDetail
	(*CreateOrderReq)(nil),         // 7: order.CreateOrderReq
	(*CreateOrderResp)(nil),        // 8: order.CreateOrderResp
	(*GetQueueStatusReq)(nil),      // 9: order.GetQueueStatusReq
	(*GetQueueStatusResp)(nil),     // 10: order.GetQueueStatusResp
	(*PayOrderReq)(nil),            // 11: order.PayOrderReq
	(*PayOrderResp)(nil),           // 12: order.PayOrderResp
	(*CancelOrderReq)(nil),         // 13: order.CancelOrderReq
	(*CancelOrderResp)(nil),        // 14: order.CancelOrderResp
	(*ApplyRefundReq)(nil),         // 15: order.ApplyRefundReq
	(*ApplyRefundResp)(nil),        // 16: order.ApplyRefundResp
	(*ListOrderReq)(nil),           // 17: order.ListOrderReq
	(*ListOrderResp)(nil),          // 18: order.ListOrderResp
	(*GetOrderDetailReq)(nil),      // 19: order.GetOrderDetailReq
	(*GetOrderDetailResp)(nil),     // 20: order.GetOrderDetailResp
	(*InventoryPreheatResult)(nil), // 21: order.InventoryPreheatResult
	(*PreheatInventoryReq)(nil),    // 22: order.PreheatInventoryReq
	(*PreheatInventoryResp)(nil),   // 23: order.PreheatInventoryResp
}
var file_order_proto_depIdxs = []int32{
	0,  // 0: order.OrderTicketInfo.buyer:type_name -> order.OrderBuyerInfo
	4,  // 1: order.OrderDetail.delivery:type_name -> order.OrderDeliveryInfo
	1,  // 2: order.OrderDetail.tickets:type_name -> order.OrderTicketInfo
	2,  // 3: order.OrderDetail.payment:type_name -> order.OrderPaymentInfo
	3,  // 4: order.OrderDetail.refund:type_name -> order.OrderRefundInfo
	5,  // 5: order.GetQueueStatusResp.order:type_name -> order.OrderSummary
	2,  // 6: order.PayOrderResp.payment:type_name -> order.OrderPaymentInfo
	3,  // 7: order.ApplyRefundResp.refund:type_name -> order.OrderRefundInfo
	5,  // 8: order.ListOrderResp.orders:type_name -> order.OrderSummary
	6,  // 9: order.GetOrderDetailResp.order:type_name -> order.OrderDetail
	21, // 10: order.PreheatInventoryResp.results:type_name -> order.InventoryPreheatResult
	22, // 11: order.OrderService.PreheatInventory:input_type -> order.PreheatInventoryReq
	7,  // 12: order.OrderService.CreateOrder:input_type -> order.CreateOrderReq
	9,  // 13: order.OrderService.GetQueueStatus:input_type -> order.GetQueueStatusReq
	11, // 14: order.OrderService.PayOrder:input_type -> order.PayOrderReq
	13, // 15: order.OrderService.CancelOrder:input_type -> order.CancelOrderReq
	15, // 16: order.OrderService.ApplyRefund:input_type -> order.ApplyRefundReq
	17, // 17: order.OrderService.ListOrder:input_type -> order.ListOrderReq
	19, // 18: order.OrderService.GetOrderDetail:input_type -> order.GetOrderDetailReq
	23, // 19: order.OrderService.PreheatInventory:output_type -> order.PreheatInventoryResp
	8,  // 20: order.OrderService.CreateOrder:output_type -> order.CreateOrderResp
	10, // 21: order.OrderService.GetQueueStatus:output_type -> order.GetQueueStatusResp
	12, // 22: order.OrderService.PayOrder:output_type -> order.PayOrderResp
	14, // 23: order.OrderService.CancelOrder:output_type -> order.CancelOrderResp
	16, // 24: order.OrderService.ApplyRefund:output_type -> order.ApplyRefundResp
	18, // 25: order.OrderService.ListOrder:output_type -> order.ListOrderResp
	20, // 26: order.OrderService.GetOrderDetail:output_type -> order.GetOrderDetailResp
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
