input {
  tcp {
    host => "0.0.0.0"
    port => 5001
    mode => "server"
    codec => json_lines
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "unknown-service" }
    }
  }

  if ![mode] {
    mutate {
      add_field => { "mode" => "unknown" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "xiaomaipro-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
  }

  stdout {
    codec => rubydebug
  }
}
