// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server/app/rpc/model"
)

func newAdminLog(db *gorm.DB, opts ...gen.DOOption) adminLog {
	_adminLog := adminLog{}

	_adminLog.adminLogDo.UseDB(db, opts...)
	_adminLog.adminLogDo.UseModel(&model.AdminLog{})

	tableName := _adminLog.adminLogDo.TableName()
	_adminLog.ALL = field.NewAsterisk(tableName)
	_adminLog.ID = field.NewInt64(tableName, "id")
	_adminLog.AdminID = field.NewInt64(tableName, "admin_id")
	_adminLog.Action = field.NewString(tableName, "action")
	_adminLog.TargetType = field.NewString(tableName, "target_type")
	_adminLog.TargetID = field.NewInt64(tableName, "target_id")
	_adminLog.Detail = field.NewString(tableName, "detail")
	_adminLog.IP = field.NewString(tableName, "ip")
	_adminLog.CreatedAt = field.NewTime(tableName, "created_at")

	_adminLog.fillFieldMap()

	return _adminLog
}

type adminLog struct {
	adminLogDo adminLogDo

	ALL        field.Asterisk
	ID         field.Int64
	AdminID    field.Int64
	Action     field.String
	TargetType field.String
	TargetID   field.Int64
	Detail     field.String
	IP         field.String
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (a adminLog) Table(newTableName string) *adminLog {
	a.adminLogDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminLog) As(alias string) *adminLog {
	a.adminLogDo.DO = *(a.adminLogDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminLog) updateTableName(table string) *adminLog {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.AdminID = field.NewInt64(table, "admin_id")
	a.Action = field.NewString(table, "action")
	a.TargetType = field.NewString(table, "target_type")
	a.TargetID = field.NewInt64(table, "target_id")
	a.Detail = field.NewString(table, "detail")
	a.IP = field.NewString(table, "ip")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *adminLog) WithContext(ctx context.Context) IAdminLogDo { return a.adminLogDo.WithContext(ctx) }

func (a adminLog) TableName() string { return a.adminLogDo.TableName() }

func (a adminLog) Alias() string { return a.adminLogDo.Alias() }

func (a adminLog) Columns(cols ...field.Expr) gen.Columns { return a.adminLogDo.Columns(cols...) }

func (a *adminLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminLog) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["admin_id"] = a.AdminID
	a.fieldMap["action"] = a.Action
	a.fieldMap["target_type"] = a.TargetType
	a.fieldMap["target_id"] = a.TargetID
	a.fieldMap["detail"] = a.Detail
	a.fieldMap["ip"] = a.IP
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a adminLog) clone(db *gorm.DB) adminLog {
	a.adminLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminLog) replaceDB(db *gorm.DB) adminLog {
	a.adminLogDo.ReplaceDB(db)
	return a
}

type adminLogDo struct{ gen.DO }

type IAdminLogDo interface {
	gen.SubQuery
	Debug() IAdminLogDo
	WithContext(ctx context.Context) IAdminLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAdminLogDo
	WriteDB() IAdminLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAdminLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAdminLogDo
	Not(conds ...gen.Condition) IAdminLogDo
	Or(conds ...gen.Condition) IAdminLogDo
	Select(conds ...field.Expr) IAdminLogDo
	Where(conds ...gen.Condition) IAdminLogDo
	Order(conds ...field.Expr) IAdminLogDo
	Distinct(cols ...field.Expr) IAdminLogDo
	Omit(cols ...field.Expr) IAdminLogDo
	Join(table schema.Tabler, on ...field.Expr) IAdminLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAdminLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAdminLogDo
	Group(cols ...field.Expr) IAdminLogDo
	Having(conds ...gen.Condition) IAdminLogDo
	Limit(limit int) IAdminLogDo
	Offset(offset int) IAdminLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminLogDo
	Unscoped() IAdminLogDo
	Create(values ...*model.AdminLog) error
	CreateInBatches(values []*model.AdminLog, batchSize int) error
	Save(values ...*model.AdminLog) error
	First() (*model.AdminLog, error)
	Take() (*model.AdminLog, error)
	Last() (*model.AdminLog, error)
	Find() ([]*model.AdminLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminLog, err error)
	FindInBatches(result *[]*model.AdminLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AdminLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAdminLogDo
	Assign(attrs ...field.AssignExpr) IAdminLogDo
	Joins(fields ...field.RelationField) IAdminLogDo
	Preload(fields ...field.RelationField) IAdminLogDo
	FirstOrInit() (*model.AdminLog, error)
	FirstOrCreate() (*model.AdminLog, error)
	FindByPage(offset int, limit int) (result []*model.AdminLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAdminLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a adminLogDo) Debug() IAdminLogDo {
	return a.withDO(a.DO.Debug())
}

func (a adminLogDo) WithContext(ctx context.Context) IAdminLogDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminLogDo) ReadDB() IAdminLogDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminLogDo) WriteDB() IAdminLogDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminLogDo) Session(config *gorm.Session) IAdminLogDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminLogDo) Clauses(conds ...clause.Expression) IAdminLogDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminLogDo) Returning(value interface{}, columns ...string) IAdminLogDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminLogDo) Not(conds ...gen.Condition) IAdminLogDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminLogDo) Or(conds ...gen.Condition) IAdminLogDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminLogDo) Select(conds ...field.Expr) IAdminLogDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminLogDo) Where(conds ...gen.Condition) IAdminLogDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminLogDo) Order(conds ...field.Expr) IAdminLogDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminLogDo) Distinct(cols ...field.Expr) IAdminLogDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminLogDo) Omit(cols ...field.Expr) IAdminLogDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminLogDo) Join(table schema.Tabler, on ...field.Expr) IAdminLogDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAdminLogDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IAdminLogDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminLogDo) Group(cols ...field.Expr) IAdminLogDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminLogDo) Having(conds ...gen.Condition) IAdminLogDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminLogDo) Limit(limit int) IAdminLogDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminLogDo) Offset(offset int) IAdminLogDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminLogDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminLogDo) Unscoped() IAdminLogDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminLogDo) Create(values ...*model.AdminLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminLogDo) CreateInBatches(values []*model.AdminLog, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminLogDo) Save(values ...*model.AdminLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminLogDo) First() (*model.AdminLog, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLog), nil
	}
}

func (a adminLogDo) Take() (*model.AdminLog, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLog), nil
	}
}

func (a adminLogDo) Last() (*model.AdminLog, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLog), nil
	}
}

func (a adminLogDo) Find() ([]*model.AdminLog, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminLog), err
}

func (a adminLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminLog, err error) {
	buf := make([]*model.AdminLog, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminLogDo) FindInBatches(result *[]*model.AdminLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminLogDo) Attrs(attrs ...field.AssignExpr) IAdminLogDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminLogDo) Assign(attrs ...field.AssignExpr) IAdminLogDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminLogDo) Joins(fields ...field.RelationField) IAdminLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminLogDo) Preload(fields ...field.RelationField) IAdminLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminLogDo) FirstOrInit() (*model.AdminLog, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLog), nil
	}
}

func (a adminLogDo) FirstOrCreate() (*model.AdminLog, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLog), nil
	}
}

func (a adminLogDo) FindByPage(offset int, limit int) (result []*model.AdminLog, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminLogDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminLogDo) Delete(models ...*model.AdminLog) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminLogDo) withDO(do gen.Dao) *adminLogDo {
	a.DO = *do.(*gen.DO)
	return a
}
