// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server/app/rpc/model"
)

func newEventFavorite(db *gorm.DB, opts ...gen.DOOption) eventFavorite {
	_eventFavorite := eventFavorite{}

	_eventFavorite.eventFavoriteDo.UseDB(db, opts...)
	_eventFavorite.eventFavoriteDo.UseModel(&model.EventFavorite{})

	tableName := _eventFavorite.eventFavoriteDo.TableName()
	_eventFavorite.ALL = field.NewAsterisk(tableName)
	_eventFavorite.ID = field.NewInt64(tableName, "id")
	_eventFavorite.UserID = field.NewInt64(tableName, "user_id")
	_eventFavorite.EventID = field.NewInt64(tableName, "event_id")
	_eventFavorite.NotifyEnabled = field.NewInt16(tableName, "notify_enabled")
	_eventFavorite.CreatedAt = field.NewTime(tableName, "created_at")

	_eventFavorite.fillFieldMap()

	return _eventFavorite
}

type eventFavorite struct {
	eventFavoriteDo eventFavoriteDo

	ALL           field.Asterisk
	ID            field.Int64
	UserID        field.Int64
	EventID       field.Int64
	NotifyEnabled field.Int16
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (e eventFavorite) Table(newTableName string) *eventFavorite {
	e.eventFavoriteDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventFavorite) As(alias string) *eventFavorite {
	e.eventFavoriteDo.DO = *(e.eventFavoriteDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventFavorite) updateTableName(table string) *eventFavorite {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.UserID = field.NewInt64(table, "user_id")
	e.EventID = field.NewInt64(table, "event_id")
	e.NotifyEnabled = field.NewInt16(table, "notify_enabled")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventFavorite) WithContext(ctx context.Context) IEventFavoriteDo {
	return e.eventFavoriteDo.WithContext(ctx)
}

func (e eventFavorite) TableName() string { return e.eventFavoriteDo.TableName() }

func (e eventFavorite) Alias() string { return e.eventFavoriteDo.Alias() }

func (e eventFavorite) Columns(cols ...field.Expr) gen.Columns {
	return e.eventFavoriteDo.Columns(cols...)
}

func (e *eventFavorite) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventFavorite) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 5)
	e.fieldMap["id"] = e.ID
	e.fieldMap["user_id"] = e.UserID
	e.fieldMap["event_id"] = e.EventID
	e.fieldMap["notify_enabled"] = e.NotifyEnabled
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventFavorite) clone(db *gorm.DB) eventFavorite {
	e.eventFavoriteDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventFavorite) replaceDB(db *gorm.DB) eventFavorite {
	e.eventFavoriteDo.ReplaceDB(db)
	return e
}

type eventFavoriteDo struct{ gen.DO }

type IEventFavoriteDo interface {
	gen.SubQuery
	Debug() IEventFavoriteDo
	WithContext(ctx context.Context) IEventFavoriteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventFavoriteDo
	WriteDB() IEventFavoriteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventFavoriteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventFavoriteDo
	Not(conds ...gen.Condition) IEventFavoriteDo
	Or(conds ...gen.Condition) IEventFavoriteDo
	Select(conds ...field.Expr) IEventFavoriteDo
	Where(conds ...gen.Condition) IEventFavoriteDo
	Order(conds ...field.Expr) IEventFavoriteDo
	Distinct(cols ...field.Expr) IEventFavoriteDo
	Omit(cols ...field.Expr) IEventFavoriteDo
	Join(table schema.Tabler, on ...field.Expr) IEventFavoriteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventFavoriteDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventFavoriteDo
	Group(cols ...field.Expr) IEventFavoriteDo
	Having(conds ...gen.Condition) IEventFavoriteDo
	Limit(limit int) IEventFavoriteDo
	Offset(offset int) IEventFavoriteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventFavoriteDo
	Unscoped() IEventFavoriteDo
	Create(values ...*model.EventFavorite) error
	CreateInBatches(values []*model.EventFavorite, batchSize int) error
	Save(values ...*model.EventFavorite) error
	First() (*model.EventFavorite, error)
	Take() (*model.EventFavorite, error)
	Last() (*model.EventFavorite, error)
	Find() ([]*model.EventFavorite, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventFavorite, err error)
	FindInBatches(result *[]*model.EventFavorite, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventFavorite) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventFavoriteDo
	Assign(attrs ...field.AssignExpr) IEventFavoriteDo
	Joins(fields ...field.RelationField) IEventFavoriteDo
	Preload(fields ...field.RelationField) IEventFavoriteDo
	FirstOrInit() (*model.EventFavorite, error)
	FirstOrCreate() (*model.EventFavorite, error)
	FindByPage(offset int, limit int) (result []*model.EventFavorite, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventFavoriteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventFavoriteDo) Debug() IEventFavoriteDo {
	return e.withDO(e.DO.Debug())
}

func (e eventFavoriteDo) WithContext(ctx context.Context) IEventFavoriteDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventFavoriteDo) ReadDB() IEventFavoriteDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventFavoriteDo) WriteDB() IEventFavoriteDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventFavoriteDo) Session(config *gorm.Session) IEventFavoriteDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventFavoriteDo) Clauses(conds ...clause.Expression) IEventFavoriteDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventFavoriteDo) Returning(value interface{}, columns ...string) IEventFavoriteDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventFavoriteDo) Not(conds ...gen.Condition) IEventFavoriteDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventFavoriteDo) Or(conds ...gen.Condition) IEventFavoriteDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventFavoriteDo) Select(conds ...field.Expr) IEventFavoriteDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventFavoriteDo) Where(conds ...gen.Condition) IEventFavoriteDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventFavoriteDo) Order(conds ...field.Expr) IEventFavoriteDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventFavoriteDo) Distinct(cols ...field.Expr) IEventFavoriteDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventFavoriteDo) Omit(cols ...field.Expr) IEventFavoriteDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventFavoriteDo) Join(table schema.Tabler, on ...field.Expr) IEventFavoriteDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventFavoriteDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventFavoriteDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventFavoriteDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventFavoriteDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventFavoriteDo) Group(cols ...field.Expr) IEventFavoriteDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventFavoriteDo) Having(conds ...gen.Condition) IEventFavoriteDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventFavoriteDo) Limit(limit int) IEventFavoriteDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventFavoriteDo) Offset(offset int) IEventFavoriteDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventFavoriteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventFavoriteDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventFavoriteDo) Unscoped() IEventFavoriteDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventFavoriteDo) Create(values ...*model.EventFavorite) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventFavoriteDo) CreateInBatches(values []*model.EventFavorite, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventFavoriteDo) Save(values ...*model.EventFavorite) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventFavoriteDo) First() (*model.EventFavorite, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventFavorite), nil
	}
}

func (e eventFavoriteDo) Take() (*model.EventFavorite, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventFavorite), nil
	}
}

func (e eventFavoriteDo) Last() (*model.EventFavorite, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventFavorite), nil
	}
}

func (e eventFavoriteDo) Find() ([]*model.EventFavorite, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventFavorite), err
}

func (e eventFavoriteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventFavorite, err error) {
	buf := make([]*model.EventFavorite, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventFavoriteDo) FindInBatches(result *[]*model.EventFavorite, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventFavoriteDo) Attrs(attrs ...field.AssignExpr) IEventFavoriteDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventFavoriteDo) Assign(attrs ...field.AssignExpr) IEventFavoriteDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventFavoriteDo) Joins(fields ...field.RelationField) IEventFavoriteDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventFavoriteDo) Preload(fields ...field.RelationField) IEventFavoriteDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventFavoriteDo) FirstOrInit() (*model.EventFavorite, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventFavorite), nil
	}
}

func (e eventFavoriteDo) FirstOrCreate() (*model.EventFavorite, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventFavorite), nil
	}
}

func (e eventFavoriteDo) FindByPage(offset int, limit int) (result []*model.EventFavorite, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventFavoriteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventFavoriteDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventFavoriteDo) Delete(models ...*model.EventFavorite) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventFavoriteDo) withDO(do gen.Dao) *eventFavoriteDo {
	e.DO = *do.(*gen.DO)
	return e
}
