// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	Address       *address
	AdminLog      *adminLog
	AdminUser     *adminUser
	Category      *category
	City          *city
	Event         *event
	EventFavorite *eventFavorite
	Notification  *notification
	OrderInfo     *orderInfo
	OrderTicket   *orderTicket
	Payment       *payment
	Refund        *refund
	TicketBuyer   *ticketBuyer
	TicketTier    *ticketTier
	User          *user
	Venue         *venue
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Address = &Q.Address
	AdminLog = &Q.AdminLog
	AdminUser = &Q.AdminUser
	Category = &Q.Category
	City = &Q.City
	Event = &Q.Event
	EventFavorite = &Q.EventFavorite
	Notification = &Q.Notification
	OrderInfo = &Q.OrderInfo
	OrderTicket = &Q.OrderTicket
	Payment = &Q.Payment
	Refund = &Q.Refund
	TicketBuyer = &Q.TicketBuyer
	TicketTier = &Q.TicketTier
	User = &Q.User
	Venue = &Q.Venue
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		Address:       newAddress(db, opts...),
		AdminLog:      newAdminLog(db, opts...),
		AdminUser:     newAdminUser(db, opts...),
		Category:      newCategory(db, opts...),
		City:          newCity(db, opts...),
		Event:         newEvent(db, opts...),
		EventFavorite: newEventFavorite(db, opts...),
		Notification:  newNotification(db, opts...),
		OrderInfo:     newOrderInfo(db, opts...),
		OrderTicket:   newOrderTicket(db, opts...),
		Payment:       newPayment(db, opts...),
		Refund:        newRefund(db, opts...),
		TicketBuyer:   newTicketBuyer(db, opts...),
		TicketTier:    newTicketTier(db, opts...),
		User:          newUser(db, opts...),
		Venue:         newVenue(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Address       address
	AdminLog      adminLog
	AdminUser     adminUser
	Category      category
	City          city
	Event         event
	EventFavorite eventFavorite
	Notification  notification
	OrderInfo     orderInfo
	OrderTicket   orderTicket
	Payment       payment
	Refund        refund
	TicketBuyer   ticketBuyer
	TicketTier    ticketTier
	User          user
	Venue         venue
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Address:       q.Address.clone(db),
		AdminLog:      q.AdminLog.clone(db),
		AdminUser:     q.AdminUser.clone(db),
		Category:      q.Category.clone(db),
		City:          q.City.clone(db),
		Event:         q.Event.clone(db),
		EventFavorite: q.EventFavorite.clone(db),
		Notification:  q.Notification.clone(db),
		OrderInfo:     q.OrderInfo.clone(db),
		OrderTicket:   q.OrderTicket.clone(db),
		Payment:       q.Payment.clone(db),
		Refund:        q.Refund.clone(db),
		TicketBuyer:   q.TicketBuyer.clone(db),
		TicketTier:    q.TicketTier.clone(db),
		User:          q.User.clone(db),
		Venue:         q.Venue.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Address:       q.Address.replaceDB(db),
		AdminLog:      q.AdminLog.replaceDB(db),
		AdminUser:     q.AdminUser.replaceDB(db),
		Category:      q.Category.replaceDB(db),
		City:          q.City.replaceDB(db),
		Event:         q.Event.replaceDB(db),
		EventFavorite: q.EventFavorite.replaceDB(db),
		Notification:  q.Notification.replaceDB(db),
		OrderInfo:     q.OrderInfo.replaceDB(db),
		OrderTicket:   q.OrderTicket.replaceDB(db),
		Payment:       q.Payment.replaceDB(db),
		Refund:        q.Refund.replaceDB(db),
		TicketBuyer:   q.TicketBuyer.replaceDB(db),
		TicketTier:    q.TicketTier.replaceDB(db),
		User:          q.User.replaceDB(db),
		Venue:         q.Venue.replaceDB(db),
	}
}

type queryCtx struct {
	Address       IAddressDo
	AdminLog      IAdminLogDo
	AdminUser     IAdminUserDo
	Category      ICategoryDo
	City          ICityDo
	Event         IEventDo
	EventFavorite IEventFavoriteDo
	Notification  INotificationDo
	OrderInfo     IOrderInfoDo
	OrderTicket   IOrderTicketDo
	Payment       IPaymentDo
	Refund        IRefundDo
	TicketBuyer   ITicketBuyerDo
	TicketTier    ITicketTierDo
	User          IUserDo
	Venue         IVenueDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Address:       q.Address.WithContext(ctx),
		AdminLog:      q.AdminLog.WithContext(ctx),
		AdminUser:     q.AdminUser.WithContext(ctx),
		Category:      q.Category.WithContext(ctx),
		City:          q.City.WithContext(ctx),
		Event:         q.Event.WithContext(ctx),
		EventFavorite: q.EventFavorite.WithContext(ctx),
		Notification:  q.Notification.WithContext(ctx),
		OrderInfo:     q.OrderInfo.WithContext(ctx),
		OrderTicket:   q.OrderTicket.WithContext(ctx),
		Payment:       q.Payment.WithContext(ctx),
		Refund:        q.Refund.WithContext(ctx),
		TicketBuyer:   q.TicketBuyer.WithContext(ctx),
		TicketTier:    q.TicketTier.WithContext(ctx),
		User:          q.User.WithContext(ctx),
		Venue:         q.Venue.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
