// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server/app/rpc/model"
)

func newOrderInfo(db *gorm.DB, opts ...gen.DOOption) orderInfo {
	_orderInfo := orderInfo{}

	_orderInfo.orderInfoDo.UseDB(db, opts...)
	_orderInfo.orderInfoDo.UseModel(&model.OrderInfo{})

	tableName := _orderInfo.orderInfoDo.TableName()
	_orderInfo.ALL = field.NewAsterisk(tableName)
	_orderInfo.ID = field.NewInt64(tableName, "id")
	_orderInfo.OrderNo = field.NewString(tableName, "order_no")
	_orderInfo.UserID = field.NewInt64(tableName, "user_id")
	_orderInfo.EventID = field.NewInt64(tableName, "event_id")
	_orderInfo.TicketTierID = field.NewInt64(tableName, "ticket_tier_id")
	_orderInfo.Quantity = field.NewInt32(tableName, "quantity")
	_orderInfo.UnitPrice = field.NewFloat64(tableName, "unit_price")
	_orderInfo.TotalAmount = field.NewFloat64(tableName, "total_amount")
	_orderInfo.Status = field.NewInt16(tableName, "status")
	_orderInfo.CancelReason = field.NewInt16(tableName, "cancel_reason")
	_orderInfo.PayDeadline = field.NewTime(tableName, "pay_deadline")
	_orderInfo.PaidAt = field.NewTime(tableName, "paid_at")
	_orderInfo.CancelledAt = field.NewTime(tableName, "cancelled_at")
	_orderInfo.AddressID = field.NewInt64(tableName, "address_id")
	_orderInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_orderInfo.UpdatedAt = field.NewTime(tableName, "updated_at")

	_orderInfo.fillFieldMap()

	return _orderInfo
}

type orderInfo struct {
	orderInfoDo orderInfoDo

	ALL          field.Asterisk
	ID           field.Int64
	OrderNo      field.String
	UserID       field.Int64
	EventID      field.Int64
	TicketTierID field.Int64
	Quantity     field.Int32
	UnitPrice    field.Float64
	TotalAmount  field.Float64
	Status       field.Int16
	CancelReason field.Int16
	PayDeadline  field.Time
	PaidAt       field.Time
	CancelledAt  field.Time
	AddressID    field.Int64
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (o orderInfo) Table(newTableName string) *orderInfo {
	o.orderInfoDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o orderInfo) As(alias string) *orderInfo {
	o.orderInfoDo.DO = *(o.orderInfoDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *orderInfo) updateTableName(table string) *orderInfo {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.OrderNo = field.NewString(table, "order_no")
	o.UserID = field.NewInt64(table, "user_id")
	o.EventID = field.NewInt64(table, "event_id")
	o.TicketTierID = field.NewInt64(table, "ticket_tier_id")
	o.Quantity = field.NewInt32(table, "quantity")
	o.UnitPrice = field.NewFloat64(table, "unit_price")
	o.TotalAmount = field.NewFloat64(table, "total_amount")
	o.Status = field.NewInt16(table, "status")
	o.CancelReason = field.NewInt16(table, "cancel_reason")
	o.PayDeadline = field.NewTime(table, "pay_deadline")
	o.PaidAt = field.NewTime(table, "paid_at")
	o.CancelledAt = field.NewTime(table, "cancelled_at")
	o.AddressID = field.NewInt64(table, "address_id")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")

	o.fillFieldMap()

	return o
}

func (o *orderInfo) WithContext(ctx context.Context) IOrderInfoDo {
	return o.orderInfoDo.WithContext(ctx)
}

func (o orderInfo) TableName() string { return o.orderInfoDo.TableName() }

func (o orderInfo) Alias() string { return o.orderInfoDo.Alias() }

func (o orderInfo) Columns(cols ...field.Expr) gen.Columns { return o.orderInfoDo.Columns(cols...) }

func (o *orderInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *orderInfo) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 16)
	o.fieldMap["id"] = o.ID
	o.fieldMap["order_no"] = o.OrderNo
	o.fieldMap["user_id"] = o.UserID
	o.fieldMap["event_id"] = o.EventID
	o.fieldMap["ticket_tier_id"] = o.TicketTierID
	o.fieldMap["quantity"] = o.Quantity
	o.fieldMap["unit_price"] = o.UnitPrice
	o.fieldMap["total_amount"] = o.TotalAmount
	o.fieldMap["status"] = o.Status
	o.fieldMap["cancel_reason"] = o.CancelReason
	o.fieldMap["pay_deadline"] = o.PayDeadline
	o.fieldMap["paid_at"] = o.PaidAt
	o.fieldMap["cancelled_at"] = o.CancelledAt
	o.fieldMap["address_id"] = o.AddressID
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
}

func (o orderInfo) clone(db *gorm.DB) orderInfo {
	o.orderInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o orderInfo) replaceDB(db *gorm.DB) orderInfo {
	o.orderInfoDo.ReplaceDB(db)
	return o
}

type orderInfoDo struct{ gen.DO }

type IOrderInfoDo interface {
	gen.SubQuery
	Debug() IOrderInfoDo
	WithContext(ctx context.Context) IOrderInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOrderInfoDo
	WriteDB() IOrderInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOrderInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOrderInfoDo
	Not(conds ...gen.Condition) IOrderInfoDo
	Or(conds ...gen.Condition) IOrderInfoDo
	Select(conds ...field.Expr) IOrderInfoDo
	Where(conds ...gen.Condition) IOrderInfoDo
	Order(conds ...field.Expr) IOrderInfoDo
	Distinct(cols ...field.Expr) IOrderInfoDo
	Omit(cols ...field.Expr) IOrderInfoDo
	Join(table schema.Tabler, on ...field.Expr) IOrderInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOrderInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOrderInfoDo
	Group(cols ...field.Expr) IOrderInfoDo
	Having(conds ...gen.Condition) IOrderInfoDo
	Limit(limit int) IOrderInfoDo
	Offset(offset int) IOrderInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOrderInfoDo
	Unscoped() IOrderInfoDo
	Create(values ...*model.OrderInfo) error
	CreateInBatches(values []*model.OrderInfo, batchSize int) error
	Save(values ...*model.OrderInfo) error
	First() (*model.OrderInfo, error)
	Take() (*model.OrderInfo, error)
	Last() (*model.OrderInfo, error)
	Find() ([]*model.OrderInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrderInfo, err error)
	FindInBatches(result *[]*model.OrderInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.OrderInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOrderInfoDo
	Assign(attrs ...field.AssignExpr) IOrderInfoDo
	Joins(fields ...field.RelationField) IOrderInfoDo
	Preload(fields ...field.RelationField) IOrderInfoDo
	FirstOrInit() (*model.OrderInfo, error)
	FirstOrCreate() (*model.OrderInfo, error)
	FindByPage(offset int, limit int) (result []*model.OrderInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOrderInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o orderInfoDo) Debug() IOrderInfoDo {
	return o.withDO(o.DO.Debug())
}

func (o orderInfoDo) WithContext(ctx context.Context) IOrderInfoDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orderInfoDo) ReadDB() IOrderInfoDo {
	return o.Clauses(dbresolver.Read)
}

func (o orderInfoDo) WriteDB() IOrderInfoDo {
	return o.Clauses(dbresolver.Write)
}

func (o orderInfoDo) Session(config *gorm.Session) IOrderInfoDo {
	return o.withDO(o.DO.Session(config))
}

func (o orderInfoDo) Clauses(conds ...clause.Expression) IOrderInfoDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orderInfoDo) Returning(value interface{}, columns ...string) IOrderInfoDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orderInfoDo) Not(conds ...gen.Condition) IOrderInfoDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orderInfoDo) Or(conds ...gen.Condition) IOrderInfoDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orderInfoDo) Select(conds ...field.Expr) IOrderInfoDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orderInfoDo) Where(conds ...gen.Condition) IOrderInfoDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orderInfoDo) Order(conds ...field.Expr) IOrderInfoDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orderInfoDo) Distinct(cols ...field.Expr) IOrderInfoDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orderInfoDo) Omit(cols ...field.Expr) IOrderInfoDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orderInfoDo) Join(table schema.Tabler, on ...field.Expr) IOrderInfoDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orderInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOrderInfoDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orderInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IOrderInfoDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orderInfoDo) Group(cols ...field.Expr) IOrderInfoDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orderInfoDo) Having(conds ...gen.Condition) IOrderInfoDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orderInfoDo) Limit(limit int) IOrderInfoDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orderInfoDo) Offset(offset int) IOrderInfoDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orderInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOrderInfoDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orderInfoDo) Unscoped() IOrderInfoDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orderInfoDo) Create(values ...*model.OrderInfo) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orderInfoDo) CreateInBatches(values []*model.OrderInfo, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orderInfoDo) Save(values ...*model.OrderInfo) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orderInfoDo) First() (*model.OrderInfo, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderInfo), nil
	}
}

func (o orderInfoDo) Take() (*model.OrderInfo, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderInfo), nil
	}
}

func (o orderInfoDo) Last() (*model.OrderInfo, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderInfo), nil
	}
}

func (o orderInfoDo) Find() ([]*model.OrderInfo, error) {
	result, err := o.DO.Find()
	return result.([]*model.OrderInfo), err
}

func (o orderInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrderInfo, err error) {
	buf := make([]*model.OrderInfo, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orderInfoDo) FindInBatches(result *[]*model.OrderInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orderInfoDo) Attrs(attrs ...field.AssignExpr) IOrderInfoDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orderInfoDo) Assign(attrs ...field.AssignExpr) IOrderInfoDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orderInfoDo) Joins(fields ...field.RelationField) IOrderInfoDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orderInfoDo) Preload(fields ...field.RelationField) IOrderInfoDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orderInfoDo) FirstOrInit() (*model.OrderInfo, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderInfo), nil
	}
}

func (o orderInfoDo) FirstOrCreate() (*model.OrderInfo, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderInfo), nil
	}
}

func (o orderInfoDo) FindByPage(offset int, limit int) (result []*model.OrderInfo, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orderInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orderInfoDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orderInfoDo) Delete(models ...*model.OrderInfo) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orderInfoDo) withDO(do gen.Dao) *orderInfoDo {
	o.DO = *do.(*gen.DO)
	return o
}
