// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server/app/rpc/model"
)

func newTicketBuyer(db *gorm.DB, opts ...gen.DOOption) ticketBuyer {
	_ticketBuyer := ticketBuyer{}

	_ticketBuyer.ticketBuyerDo.UseDB(db, opts...)
	_ticketBuyer.ticketBuyerDo.UseModel(&model.TicketBuyer{})

	tableName := _ticketBuyer.ticketBuyerDo.TableName()
	_ticketBuyer.ALL = field.NewAsterisk(tableName)
	_ticketBuyer.ID = field.NewInt64(tableName, "id")
	_ticketBuyer.UserID = field.NewInt64(tableName, "user_id")
	_ticketBuyer.Name = field.NewString(tableName, "name")
	_ticketBuyer.IDCard = field.NewString(tableName, "id_card")
	_ticketBuyer.Phone = field.NewString(tableName, "phone")
	_ticketBuyer.IsDefault = field.NewInt16(tableName, "is_default")
	_ticketBuyer.CreatedAt = field.NewTime(tableName, "created_at")
	_ticketBuyer.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ticketBuyer.fillFieldMap()

	return _ticketBuyer
}

type ticketBuyer struct {
	ticketBuyerDo ticketBuyerDo

	ALL       field.Asterisk
	ID        field.Int64
	UserID    field.Int64
	Name      field.String
	IDCard    field.String
	Phone     field.String
	IsDefault field.Int16
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (t ticketBuyer) Table(newTableName string) *ticketBuyer {
	t.ticketBuyerDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t ticketBuyer) As(alias string) *ticketBuyer {
	t.ticketBuyerDo.DO = *(t.ticketBuyerDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *ticketBuyer) updateTableName(table string) *ticketBuyer {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.UserID = field.NewInt64(table, "user_id")
	t.Name = field.NewString(table, "name")
	t.IDCard = field.NewString(table, "id_card")
	t.Phone = field.NewString(table, "phone")
	t.IsDefault = field.NewInt16(table, "is_default")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *ticketBuyer) WithContext(ctx context.Context) ITicketBuyerDo {
	return t.ticketBuyerDo.WithContext(ctx)
}

func (t ticketBuyer) TableName() string { return t.ticketBuyerDo.TableName() }

func (t ticketBuyer) Alias() string { return t.ticketBuyerDo.Alias() }

func (t ticketBuyer) Columns(cols ...field.Expr) gen.Columns { return t.ticketBuyerDo.Columns(cols...) }

func (t *ticketBuyer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *ticketBuyer) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["name"] = t.Name
	t.fieldMap["id_card"] = t.IDCard
	t.fieldMap["phone"] = t.Phone
	t.fieldMap["is_default"] = t.IsDefault
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t ticketBuyer) clone(db *gorm.DB) ticketBuyer {
	t.ticketBuyerDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t ticketBuyer) replaceDB(db *gorm.DB) ticketBuyer {
	t.ticketBuyerDo.ReplaceDB(db)
	return t
}

type ticketBuyerDo struct{ gen.DO }

type ITicketBuyerDo interface {
	gen.SubQuery
	Debug() ITicketBuyerDo
	WithContext(ctx context.Context) ITicketBuyerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITicketBuyerDo
	WriteDB() ITicketBuyerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITicketBuyerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITicketBuyerDo
	Not(conds ...gen.Condition) ITicketBuyerDo
	Or(conds ...gen.Condition) ITicketBuyerDo
	Select(conds ...field.Expr) ITicketBuyerDo
	Where(conds ...gen.Condition) ITicketBuyerDo
	Order(conds ...field.Expr) ITicketBuyerDo
	Distinct(cols ...field.Expr) ITicketBuyerDo
	Omit(cols ...field.Expr) ITicketBuyerDo
	Join(table schema.Tabler, on ...field.Expr) ITicketBuyerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITicketBuyerDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITicketBuyerDo
	Group(cols ...field.Expr) ITicketBuyerDo
	Having(conds ...gen.Condition) ITicketBuyerDo
	Limit(limit int) ITicketBuyerDo
	Offset(offset int) ITicketBuyerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITicketBuyerDo
	Unscoped() ITicketBuyerDo
	Create(values ...*model.TicketBuyer) error
	CreateInBatches(values []*model.TicketBuyer, batchSize int) error
	Save(values ...*model.TicketBuyer) error
	First() (*model.TicketBuyer, error)
	Take() (*model.TicketBuyer, error)
	Last() (*model.TicketBuyer, error)
	Find() ([]*model.TicketBuyer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TicketBuyer, err error)
	FindInBatches(result *[]*model.TicketBuyer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TicketBuyer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITicketBuyerDo
	Assign(attrs ...field.AssignExpr) ITicketBuyerDo
	Joins(fields ...field.RelationField) ITicketBuyerDo
	Preload(fields ...field.RelationField) ITicketBuyerDo
	FirstOrInit() (*model.TicketBuyer, error)
	FirstOrCreate() (*model.TicketBuyer, error)
	FindByPage(offset int, limit int) (result []*model.TicketBuyer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITicketBuyerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t ticketBuyerDo) Debug() ITicketBuyerDo {
	return t.withDO(t.DO.Debug())
}

func (t ticketBuyerDo) WithContext(ctx context.Context) ITicketBuyerDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t ticketBuyerDo) ReadDB() ITicketBuyerDo {
	return t.Clauses(dbresolver.Read)
}

func (t ticketBuyerDo) WriteDB() ITicketBuyerDo {
	return t.Clauses(dbresolver.Write)
}

func (t ticketBuyerDo) Session(config *gorm.Session) ITicketBuyerDo {
	return t.withDO(t.DO.Session(config))
}

func (t ticketBuyerDo) Clauses(conds ...clause.Expression) ITicketBuyerDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t ticketBuyerDo) Returning(value interface{}, columns ...string) ITicketBuyerDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t ticketBuyerDo) Not(conds ...gen.Condition) ITicketBuyerDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t ticketBuyerDo) Or(conds ...gen.Condition) ITicketBuyerDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t ticketBuyerDo) Select(conds ...field.Expr) ITicketBuyerDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t ticketBuyerDo) Where(conds ...gen.Condition) ITicketBuyerDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t ticketBuyerDo) Order(conds ...field.Expr) ITicketBuyerDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t ticketBuyerDo) Distinct(cols ...field.Expr) ITicketBuyerDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t ticketBuyerDo) Omit(cols ...field.Expr) ITicketBuyerDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t ticketBuyerDo) Join(table schema.Tabler, on ...field.Expr) ITicketBuyerDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t ticketBuyerDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITicketBuyerDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t ticketBuyerDo) RightJoin(table schema.Tabler, on ...field.Expr) ITicketBuyerDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t ticketBuyerDo) Group(cols ...field.Expr) ITicketBuyerDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t ticketBuyerDo) Having(conds ...gen.Condition) ITicketBuyerDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t ticketBuyerDo) Limit(limit int) ITicketBuyerDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t ticketBuyerDo) Offset(offset int) ITicketBuyerDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t ticketBuyerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITicketBuyerDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t ticketBuyerDo) Unscoped() ITicketBuyerDo {
	return t.withDO(t.DO.Unscoped())
}

func (t ticketBuyerDo) Create(values ...*model.TicketBuyer) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t ticketBuyerDo) CreateInBatches(values []*model.TicketBuyer, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t ticketBuyerDo) Save(values ...*model.TicketBuyer) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t ticketBuyerDo) First() (*model.TicketBuyer, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketBuyer), nil
	}
}

func (t ticketBuyerDo) Take() (*model.TicketBuyer, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketBuyer), nil
	}
}

func (t ticketBuyerDo) Last() (*model.TicketBuyer, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketBuyer), nil
	}
}

func (t ticketBuyerDo) Find() ([]*model.TicketBuyer, error) {
	result, err := t.DO.Find()
	return result.([]*model.TicketBuyer), err
}

func (t ticketBuyerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TicketBuyer, err error) {
	buf := make([]*model.TicketBuyer, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t ticketBuyerDo) FindInBatches(result *[]*model.TicketBuyer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t ticketBuyerDo) Attrs(attrs ...field.AssignExpr) ITicketBuyerDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t ticketBuyerDo) Assign(attrs ...field.AssignExpr) ITicketBuyerDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t ticketBuyerDo) Joins(fields ...field.RelationField) ITicketBuyerDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t ticketBuyerDo) Preload(fields ...field.RelationField) ITicketBuyerDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t ticketBuyerDo) FirstOrInit() (*model.TicketBuyer, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketBuyer), nil
	}
}

func (t ticketBuyerDo) FirstOrCreate() (*model.TicketBuyer, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketBuyer), nil
	}
}

func (t ticketBuyerDo) FindByPage(offset int, limit int) (result []*model.TicketBuyer, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t ticketBuyerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t ticketBuyerDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t ticketBuyerDo) Delete(models ...*model.TicketBuyer) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *ticketBuyerDo) withDO(do gen.Dao) *ticketBuyerDo {
	t.DO = *do.(*gen.DO)
	return t
}
