// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"server/app/rpc/model"
)

func newTicketTier(db *gorm.DB, opts ...gen.DOOption) ticketTier {
	_ticketTier := ticketTier{}

	_ticketTier.ticketTierDo.UseDB(db, opts...)
	_ticketTier.ticketTierDo.UseModel(&model.TicketTier{})

	tableName := _ticketTier.ticketTierDo.TableName()
	_ticketTier.ALL = field.NewAsterisk(tableName)
	_ticketTier.ID = field.NewInt64(tableName, "id")
	_ticketTier.EventID = field.NewInt64(tableName, "event_id")
	_ticketTier.Name = field.NewString(tableName, "name")
	_ticketTier.Price = field.NewFloat64(tableName, "price")
	_ticketTier.TotalStock = field.NewInt32(tableName, "total_stock")
	_ticketTier.SoldCount = field.NewInt32(tableName, "sold_count")
	_ticketTier.LockedCount = field.NewInt32(tableName, "locked_count")
	_ticketTier.Status = field.NewInt16(tableName, "status")
	_ticketTier.SortOrder = field.NewInt32(tableName, "sort_order")
	_ticketTier.CreatedAt = field.NewTime(tableName, "created_at")
	_ticketTier.UpdatedAt = field.NewTime(tableName, "updated_at")

	_ticketTier.fillFieldMap()

	return _ticketTier
}

type ticketTier struct {
	ticketTierDo ticketTierDo

	ALL         field.Asterisk
	ID          field.Int64
	EventID     field.Int64
	Name        field.String
	Price       field.Float64
	TotalStock  field.Int32
	SoldCount   field.Int32
	LockedCount field.Int32
	Status      field.Int16
	SortOrder   field.Int32
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (t ticketTier) Table(newTableName string) *ticketTier {
	t.ticketTierDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t ticketTier) As(alias string) *ticketTier {
	t.ticketTierDo.DO = *(t.ticketTierDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *ticketTier) updateTableName(table string) *ticketTier {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.EventID = field.NewInt64(table, "event_id")
	t.Name = field.NewString(table, "name")
	t.Price = field.NewFloat64(table, "price")
	t.TotalStock = field.NewInt32(table, "total_stock")
	t.SoldCount = field.NewInt32(table, "sold_count")
	t.LockedCount = field.NewInt32(table, "locked_count")
	t.Status = field.NewInt16(table, "status")
	t.SortOrder = field.NewInt32(table, "sort_order")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *ticketTier) WithContext(ctx context.Context) ITicketTierDo {
	return t.ticketTierDo.WithContext(ctx)
}

func (t ticketTier) TableName() string { return t.ticketTierDo.TableName() }

func (t ticketTier) Alias() string { return t.ticketTierDo.Alias() }

func (t ticketTier) Columns(cols ...field.Expr) gen.Columns { return t.ticketTierDo.Columns(cols...) }

func (t *ticketTier) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *ticketTier) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 11)
	t.fieldMap["id"] = t.ID
	t.fieldMap["event_id"] = t.EventID
	t.fieldMap["name"] = t.Name
	t.fieldMap["price"] = t.Price
	t.fieldMap["total_stock"] = t.TotalStock
	t.fieldMap["sold_count"] = t.SoldCount
	t.fieldMap["locked_count"] = t.LockedCount
	t.fieldMap["status"] = t.Status
	t.fieldMap["sort_order"] = t.SortOrder
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t ticketTier) clone(db *gorm.DB) ticketTier {
	t.ticketTierDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t ticketTier) replaceDB(db *gorm.DB) ticketTier {
	t.ticketTierDo.ReplaceDB(db)
	return t
}

type ticketTierDo struct{ gen.DO }

type ITicketTierDo interface {
	gen.SubQuery
	Debug() ITicketTierDo
	WithContext(ctx context.Context) ITicketTierDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITicketTierDo
	WriteDB() ITicketTierDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITicketTierDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITicketTierDo
	Not(conds ...gen.Condition) ITicketTierDo
	Or(conds ...gen.Condition) ITicketTierDo
	Select(conds ...field.Expr) ITicketTierDo
	Where(conds ...gen.Condition) ITicketTierDo
	Order(conds ...field.Expr) ITicketTierDo
	Distinct(cols ...field.Expr) ITicketTierDo
	Omit(cols ...field.Expr) ITicketTierDo
	Join(table schema.Tabler, on ...field.Expr) ITicketTierDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITicketTierDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITicketTierDo
	Group(cols ...field.Expr) ITicketTierDo
	Having(conds ...gen.Condition) ITicketTierDo
	Limit(limit int) ITicketTierDo
	Offset(offset int) ITicketTierDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITicketTierDo
	Unscoped() ITicketTierDo
	Create(values ...*model.TicketTier) error
	CreateInBatches(values []*model.TicketTier, batchSize int) error
	Save(values ...*model.TicketTier) error
	First() (*model.TicketTier, error)
	Take() (*model.TicketTier, error)
	Last() (*model.TicketTier, error)
	Find() ([]*model.TicketTier, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TicketTier, err error)
	FindInBatches(result *[]*model.TicketTier, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TicketTier) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITicketTierDo
	Assign(attrs ...field.AssignExpr) ITicketTierDo
	Joins(fields ...field.RelationField) ITicketTierDo
	Preload(fields ...field.RelationField) ITicketTierDo
	FirstOrInit() (*model.TicketTier, error)
	FirstOrCreate() (*model.TicketTier, error)
	FindByPage(offset int, limit int) (result []*model.TicketTier, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITicketTierDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t ticketTierDo) Debug() ITicketTierDo {
	return t.withDO(t.DO.Debug())
}

func (t ticketTierDo) WithContext(ctx context.Context) ITicketTierDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t ticketTierDo) ReadDB() ITicketTierDo {
	return t.Clauses(dbresolver.Read)
}

func (t ticketTierDo) WriteDB() ITicketTierDo {
	return t.Clauses(dbresolver.Write)
}

func (t ticketTierDo) Session(config *gorm.Session) ITicketTierDo {
	return t.withDO(t.DO.Session(config))
}

func (t ticketTierDo) Clauses(conds ...clause.Expression) ITicketTierDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t ticketTierDo) Returning(value interface{}, columns ...string) ITicketTierDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t ticketTierDo) Not(conds ...gen.Condition) ITicketTierDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t ticketTierDo) Or(conds ...gen.Condition) ITicketTierDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t ticketTierDo) Select(conds ...field.Expr) ITicketTierDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t ticketTierDo) Where(conds ...gen.Condition) ITicketTierDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t ticketTierDo) Order(conds ...field.Expr) ITicketTierDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t ticketTierDo) Distinct(cols ...field.Expr) ITicketTierDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t ticketTierDo) Omit(cols ...field.Expr) ITicketTierDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t ticketTierDo) Join(table schema.Tabler, on ...field.Expr) ITicketTierDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t ticketTierDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITicketTierDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t ticketTierDo) RightJoin(table schema.Tabler, on ...field.Expr) ITicketTierDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t ticketTierDo) Group(cols ...field.Expr) ITicketTierDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t ticketTierDo) Having(conds ...gen.Condition) ITicketTierDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t ticketTierDo) Limit(limit int) ITicketTierDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t ticketTierDo) Offset(offset int) ITicketTierDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t ticketTierDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITicketTierDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t ticketTierDo) Unscoped() ITicketTierDo {
	return t.withDO(t.DO.Unscoped())
}

func (t ticketTierDo) Create(values ...*model.TicketTier) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t ticketTierDo) CreateInBatches(values []*model.TicketTier, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t ticketTierDo) Save(values ...*model.TicketTier) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t ticketTierDo) First() (*model.TicketTier, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketTier), nil
	}
}

func (t ticketTierDo) Take() (*model.TicketTier, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketTier), nil
	}
}

func (t ticketTierDo) Last() (*model.TicketTier, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketTier), nil
	}
}

func (t ticketTierDo) Find() ([]*model.TicketTier, error) {
	result, err := t.DO.Find()
	return result.([]*model.TicketTier), err
}

func (t ticketTierDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TicketTier, err error) {
	buf := make([]*model.TicketTier, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t ticketTierDo) FindInBatches(result *[]*model.TicketTier, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t ticketTierDo) Attrs(attrs ...field.AssignExpr) ITicketTierDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t ticketTierDo) Assign(attrs ...field.AssignExpr) ITicketTierDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t ticketTierDo) Joins(fields ...field.RelationField) ITicketTierDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t ticketTierDo) Preload(fields ...field.RelationField) ITicketTierDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t ticketTierDo) FirstOrInit() (*model.TicketTier, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketTier), nil
	}
}

func (t ticketTierDo) FirstOrCreate() (*model.TicketTier, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TicketTier), nil
	}
}

func (t ticketTierDo) FindByPage(offset int, limit int) (result []*model.TicketTier, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t ticketTierDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t ticketTierDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t ticketTierDo) Delete(models ...*model.TicketTier) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *ticketTierDo) withDO(do gen.Dao) *ticketTierDo {
	t.DO = *do.(*gen.DO)
	return t
}
