// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"server/app/rpc/user/internal/logic"
	"server/app/rpc/user/internal/svc"
	"server/app/rpc/user/userpb/userpb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	userpb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// --- 认证相关 ---
func (s *UserServiceServer) Register(ctx context.Context, in *userpb.RegisterReq) (*userpb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *userpb.LoginReq) (*userpb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) RefreshToken(ctx context.Context, in *userpb.RefreshTokenReq) (*userpb.RefreshTokenResp, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *UserServiceServer) Logout(ctx context.Context, in *userpb.LogoutReq) (*userpb.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *UserServiceServer) ValidateToken(ctx context.Context, in *userpb.ValidateTokenReq) (*userpb.ValidateTokenResp, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

// --- 用户信息 ---
func (s *UserServiceServer) GetUserInfo(ctx context.Context, in *userpb.GetUserInfoReq) (*userpb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServiceServer) UpdateUserInfo(ctx context.Context, in *userpb.UpdateUserInfoReq) (*userpb.UpdateUserInfoResp, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *UserServiceServer) ChangePassword(ctx context.Context, in *userpb.ChangePasswordReq) (*userpb.ChangePasswordResp, error) {
	l := logic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

func (s *UserServiceServer) VerifyRealName(ctx context.Context, in *userpb.VerifyRealNameReq) (*userpb.VerifyRealNameResp, error) {
	l := logic.NewVerifyRealNameLogic(ctx, s.svcCtx)
	return l.VerifyRealName(in)
}

// --- 收货地址 ---
func (s *UserServiceServer) CreateAddress(ctx context.Context, in *userpb.CreateAddressReq) (*userpb.CreateAddressResp, error) {
	l := logic.NewCreateAddressLogic(ctx, s.svcCtx)
	return l.CreateAddress(in)
}

func (s *UserServiceServer) UpdateAddress(ctx context.Context, in *userpb.UpdateAddressReq) (*userpb.UpdateAddressResp, error) {
	l := logic.NewUpdateAddressLogic(ctx, s.svcCtx)
	return l.UpdateAddress(in)
}

func (s *UserServiceServer) DeleteAddress(ctx context.Context, in *userpb.DeleteAddressReq) (*userpb.DeleteAddressResp, error) {
	l := logic.NewDeleteAddressLogic(ctx, s.svcCtx)
	return l.DeleteAddress(in)
}

func (s *UserServiceServer) ListAddress(ctx context.Context, in *userpb.ListAddressReq) (*userpb.ListAddressResp, error) {
	l := logic.NewListAddressLogic(ctx, s.svcCtx)
	return l.ListAddress(in)
}

func (s *UserServiceServer) SetDefaultAddress(ctx context.Context, in *userpb.SetDefaultAddressReq) (*userpb.SetDefaultAddressResp, error) {
	l := logic.NewSetDefaultAddressLogic(ctx, s.svcCtx)
	return l.SetDefaultAddress(in)
}

// --- 常用购票人 ---
func (s *UserServiceServer) CreateTicketBuyer(ctx context.Context, in *userpb.CreateTicketBuyerReq) (*userpb.CreateTicketBuyerResp, error) {
	l := logic.NewCreateTicketBuyerLogic(ctx, s.svcCtx)
	return l.CreateTicketBuyer(in)
}

func (s *UserServiceServer) UpdateTicketBuyer(ctx context.Context, in *userpb.UpdateTicketBuyerReq) (*userpb.UpdateTicketBuyerResp, error) {
	l := logic.NewUpdateTicketBuyerLogic(ctx, s.svcCtx)
	return l.UpdateTicketBuyer(in)
}

func (s *UserServiceServer) DeleteTicketBuyer(ctx context.Context, in *userpb.DeleteTicketBuyerReq) (*userpb.DeleteTicketBuyerResp, error) {
	l := logic.NewDeleteTicketBuyerLogic(ctx, s.svcCtx)
	return l.DeleteTicketBuyer(in)
}

func (s *UserServiceServer) ListTicketBuyer(ctx context.Context, in *userpb.ListTicketBuyerReq) (*userpb.ListTicketBuyerResp, error) {
	l := logic.NewListTicketBuyerLogic(ctx, s.svcCtx)
	return l.ListTicketBuyer(in)
}

func (s *UserServiceServer) SetDefaultTicketBuyer(ctx context.Context, in *userpb.SetDefaultTicketBuyerReq) (*userpb.SetDefaultTicketBuyerResp, error) {
	l := logic.NewSetDefaultTicketBuyerLogic(ctx, s.svcCtx)
	return l.SetDefaultTicketBuyer(in)
}
