// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	Id         string `json:"id"`
	Phone      string `json:"phone"`
	Email      string `json:"email"`
	Nickname   string `json:"nickname"`
	Avatar     string `json:"avatar"`
	Status     int32  `json:"status"`
	IsVerified bool   `json:"isVerified"`
	RealName   string `json:"realName,optional"`
	CreatedAt  string `json:"createdAt"`
}

type AddressInfo struct {
	Id            string `json:"id"`
	ReceiverName  string `json:"receiverName"`
	ReceiverPhone string `json:"receiverPhone"`
	Province      string `json:"province"`
	City          string `json:"city"`
	District      string `json:"district"`
	Detail        string `json:"detail"`
	IsDefault     bool   `json:"isDefault"`
	CreatedAt     string `json:"createdAt"`
}

type TicketBuyerInfo struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	IdCard    string `json:"idCard"`
	Phone     string `json:"phone"`
	IsDefault bool   `json:"isDefault"`
	CreatedAt string `json:"createdAt"`
}

type RegisterReq struct {
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
	Code     string `json:"code,optional"`
}

type LoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type LogoutReq struct {
	RefreshToken string `json:"refreshToken,optional"`
}

type AuthPayload struct {
	UserId       string   `json:"userId"`
	AccessToken  string   `json:"accessToken"`
	RefreshToken string   `json:"refreshToken"`
	ExpiresIn    int64    `json:"expiresIn"`
	UserInfo     UserInfo `json:"userInfo"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
}

type ValidateTokenResp struct {
	Valid    bool     `json:"valid"`
	UserId   string   `json:"userId"`
	Status   int32    `json:"status"`
	UserInfo UserInfo `json:"userInfo"`
}

type OperationResp struct {
	Success bool `json:"success"`
}

type UpdateProfileReq struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Email    string `json:"email,optional"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CreateTicketBuyerReq struct {
	Name      string `json:"name"`
	IdCard    string `json:"idCard,optional"`
	Phone     string `json:"phone,optional"`
	IsDefault bool   `json:"isDefault"`
}

type UpdateTicketBuyerReq struct {
	BuyerId   string `json:"buyerId"`
	Name      string `json:"name,optional"`
	IdCard    string `json:"idCard,optional"`
	Phone     string `json:"phone,optional"`
	IsDefault bool   `json:"isDefault"`
}

type DeleteTicketBuyerReq struct {
	BuyerId string `json:"buyerId"`
}

type SetDefaultTicketBuyerReq struct {
	BuyerId string `json:"buyerId"`
}

type TicketBuyerResp struct {
	TicketBuyer TicketBuyerInfo `json:"ticketBuyer"`
}

type TicketBuyerListResp struct {
	TicketBuyers []TicketBuyerInfo `json:"ticketBuyers"`
}

type CreateAddressReq struct {
	ReceiverName  string `json:"receiverName"`
	ReceiverPhone string `json:"receiverPhone"`
	Province      string `json:"province"`
	City          string `json:"city"`
	District      string `json:"district"`
	Detail        string `json:"detail"`
	IsDefault     bool   `json:"isDefault"`
}

type UpdateAddressReq struct {
	AddressId     string `json:"addressId"`
	ReceiverName  string `json:"receiverName,optional"`
	ReceiverPhone string `json:"receiverPhone,optional"`
	Province      string `json:"province,optional"`
	City          string `json:"city,optional"`
	District      string `json:"district,optional"`
	Detail        string `json:"detail,optional"`
	IsDefault     bool   `json:"isDefault"`
}

type DeleteAddressReq struct {
	AddressId string `json:"addressId"`
}

type SetDefaultAddressReq struct {
	AddressId string `json:"addressId"`
}

type AddressResp struct {
	Address AddressInfo `json:"address"`
}

type AddressListResp struct {
	Addresses []AddressInfo `json:"addresses"`
}
