// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	ID            int64     `gorm:"column:id;primaryKey" json:"id"`
	UserID        int64     `gorm:"column:user_id;not null" json:"user_id"`
	ReceiverName  string    `gorm:"column:receiver_name;not null" json:"receiver_name"`
	ReceiverPhone string    `gorm:"column:receiver_phone;not null" json:"receiver_phone"`
	Province      string    `gorm:"column:province;not null" json:"province"`
	City          string    `gorm:"column:city;not null" json:"city"`
	District      string    `gorm:"column:district;not null" json:"district"`
	Detail        string    `gorm:"column:detail;not null" json:"detail"`
	IsDefault     int16     `gorm:"column:is_default;not null" json:"is_default"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
