// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminLog = "admin_log"

// AdminLog mapped from table <admin_log>
type AdminLog struct {
	ID         int64     `gorm:"column:id;primaryKey" json:"id"`
	AdminID    int64     `gorm:"column:admin_id;not null" json:"admin_id"`
	Action     string    `gorm:"column:action;not null" json:"action"`
	TargetType string    `gorm:"column:target_type;not null" json:"target_type"`
	TargetID   int64     `gorm:"column:target_id" json:"target_id"`
	Detail     string    `gorm:"column:detail" json:"detail"`
	IP         string    `gorm:"column:ip" json:"ip"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName AdminLog's table name
func (*AdminLog) TableName() string {
	return TableNameAdminLog
}
