// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string `gorm:"column:name;not null" json:"name"`
	Icon      string `gorm:"column:icon" json:"icon"`
	SortOrder int32  `gorm:"column:sort_order;not null" json:"sort_order"`
	Status    int16  `gorm:"column:status;not null;default:1" json:"status"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
