// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEvent = "event"

// Event mapped from table <event>
type Event struct {
	ID             int64          `gorm:"column:id;primaryKey" json:"id"`
	Title          string         `gorm:"column:title;not null" json:"title"`
	Description    string         `gorm:"column:description" json:"description"`
	PosterURL      string         `gorm:"column:poster_url" json:"poster_url"`
	CategoryID     int32          `gorm:"column:category_id;not null" json:"category_id"`
	VenueID        int64          `gorm:"column:venue_id;not null" json:"venue_id"`
	CityID         int64          `gorm:"column:city_id;not null" json:"city_id"`
	Artist         string         `gorm:"column:artist" json:"artist"`
	EventStartTime time.Time      `gorm:"column:event_start_time;not null" json:"event_start_time"`
	EventEndTime   time.Time      `gorm:"column:event_end_time;not null" json:"event_end_time"`
	SaleStartTime  time.Time      `gorm:"column:sale_start_time;not null" json:"sale_start_time"`
	SaleEndTime    time.Time      `gorm:"column:sale_end_time;not null" json:"sale_end_time"`
	Status         int16          `gorm:"column:status;not null" json:"status"`
	PurchaseLimit  int32          `gorm:"column:purchase_limit;not null;default:1" json:"purchase_limit"`
	NeedRealName   int16          `gorm:"column:need_real_name;not null" json:"need_real_name"`
	TicketType     int16          `gorm:"column:ticket_type;not null;default:1" json:"ticket_type"`
	CreatedBy      int64          `gorm:"column:created_by;not null" json:"created_by"`
	CreatedAt      time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
