// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventFavorite = "event_favorite"

// EventFavorite mapped from table <event_favorite>
type EventFavorite struct {
	ID            int64     `gorm:"column:id;primaryKey" json:"id"`
	UserID        int64     `gorm:"column:user_id;not null" json:"user_id"`
	EventID       int64     `gorm:"column:event_id;not null" json:"event_id"`
	NotifyEnabled int16     `gorm:"column:notify_enabled;not null;default:1" json:"notify_enabled"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName EventFavorite's table name
func (*EventFavorite) TableName() string {
	return TableNameEventFavorite
}
