// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotification = "notification"

// Notification mapped from table <notification>
type Notification struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Type      int16     `gorm:"column:type;not null" json:"type"`
	Title     string    `gorm:"column:title;not null" json:"title"`
	Content   string    `gorm:"column:content;not null" json:"content"`
	IsRead    int16     `gorm:"column:is_read;not null" json:"is_read"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Notification's table name
func (*Notification) TableName() string {
	return TableNameNotification
}
