// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrderInfo = "order_info"

// OrderInfo mapped from table <order_info>
type OrderInfo struct {
	ID           int64     `gorm:"column:id;primaryKey" json:"id"`
	OrderNo      string    `gorm:"column:order_no;not null" json:"order_no"`
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`
	EventID      int64     `gorm:"column:event_id;not null" json:"event_id"`
	TicketTierID int64     `gorm:"column:ticket_tier_id;not null" json:"ticket_tier_id"`
	Quantity     int32     `gorm:"column:quantity;not null" json:"quantity"`
	UnitPrice    float64   `gorm:"column:unit_price;not null" json:"unit_price"`
	TotalAmount  float64   `gorm:"column:total_amount;not null" json:"total_amount"`
	Status       int16     `gorm:"column:status;not null" json:"status"`
	CancelReason int16     `gorm:"column:cancel_reason;not null" json:"cancel_reason"`
	PayDeadline  time.Time `gorm:"column:pay_deadline" json:"pay_deadline"`
	PaidAt       time.Time `gorm:"column:paid_at" json:"paid_at"`
	CancelledAt  time.Time `gorm:"column:cancelled_at" json:"cancelled_at"`
	AddressID    int64     `gorm:"column:address_id" json:"address_id"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName OrderInfo's table name
func (*OrderInfo) TableName() string {
	return TableNameOrderInfo
}
