// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePayment = "payment"

// Payment mapped from table <payment>
type Payment struct {
	ID           int64     `gorm:"column:id;primaryKey" json:"id"`
	PaymentNo    string    `gorm:"column:payment_no;not null" json:"payment_no"`
	OrderID      int64     `gorm:"column:order_id;not null" json:"order_id"`
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`
	PayMethod    int16     `gorm:"column:pay_method;not null" json:"pay_method"`
	Amount       float64   `gorm:"column:amount;not null" json:"amount"`
	Status       int16     `gorm:"column:status;not null" json:"status"`
	TradeNo      string    `gorm:"column:trade_no" json:"trade_no"`
	PaidAt       time.Time `gorm:"column:paid_at" json:"paid_at"`
	CallbackData string    `gorm:"column:callback_data" json:"callback_data"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
