// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTicketBuyer = "ticket_buyer"

// TicketBuyer mapped from table <ticket_buyer>
type TicketBuyer struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	IDCard    string    `gorm:"column:id_card" json:"id_card"`
	Phone     string    `gorm:"column:phone" json:"phone"`
	IsDefault int16     `gorm:"column:is_default;not null" json:"is_default"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TicketBuyer's table name
func (*TicketBuyer) TableName() string {
	return TableNameTicketBuyer
}
