// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTicketTier = "ticket_tier"

// TicketTier mapped from table <ticket_tier>
type TicketTier struct {
	ID          int64     `gorm:"column:id;primaryKey" json:"id"`
	EventID     int64     `gorm:"column:event_id;not null" json:"event_id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Price       float64   `gorm:"column:price;not null" json:"price"`
	TotalStock  int32     `gorm:"column:total_stock;not null" json:"total_stock"`
	SoldCount   int32     `gorm:"column:sold_count;not null" json:"sold_count"`
	LockedCount int32     `gorm:"column:locked_count;not null" json:"locked_count"`
	Status      int16     `gorm:"column:status;not null;default:1" json:"status"`
	SortOrder   int32     `gorm:"column:sort_order;not null" json:"sort_order"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TicketTier's table name
func (*TicketTier) TableName() string {
	return TableNameTicketTier
}
