// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVenue = "venue"

// Venue mapped from table <venue>
type Venue struct {
	ID          int64     `gorm:"column:id;primaryKey" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	CityID      int64     `gorm:"column:city_id;not null" json:"city_id"`
	Address     string    `gorm:"column:address;not null" json:"address"`
	Capacity    int32     `gorm:"column:capacity" json:"capacity"`
	SeatMapURL  string    `gorm:"column:seat_map_url" json:"seat_map_url"`
	Description string    `gorm:"column:description" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Venue's table name
func (*Venue) TableName() string {
	return TableNameVenue
}
