// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: program.proto

package programpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	mi := &file_program_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CategoryInfo) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CategoryInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityInfo) Reset() {
	*x = CityInfo{}
	mi := &file_program_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityInfo) ProtoMessage() {}

func (x *CityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityInfo.ProtoReflect.Descriptor instead.
func (*CityInfo) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{1}
}

func (x *CityInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VenueInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Capacity      int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	SeatMapUrl    string                 `protobuf:"bytes,6,opt,name=seat_map_url,json=seatMapUrl,proto3" json:"seat_map_url,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VenueInfo) Reset() {
	*x = VenueInfo{}
	mi := &file_program_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VenueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VenueInfo) ProtoMessage() {}

func (x *VenueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VenueInfo.ProtoReflect.Descriptor instead.
func (*VenueInfo) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{2}
}

func (x *VenueInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VenueInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VenueInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *VenueInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VenueInfo) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *VenueInfo) GetSeatMapUrl() string {
	if x != nil {
		return x.SeatMapUrl
	}
	return ""
}

func (x *VenueInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TicketTierInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	TotalStock    int32                  `protobuf:"varint,5,opt,name=total_stock,json=totalStock,proto3" json:"total_stock,omitempty"`
	SoldCount     int32                  `protobuf:"varint,6,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	LockedCount   int32                  `protobuf:"varint,7,opt,name=locked_count,json=lockedCount,proto3" json:"locked_count,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	SortOrder     int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	RemainStock   int32                  `protobuf:"varint,10,opt,name=remain_stock,json=remainStock,proto3" json:"remain_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketTierInfo) Reset() {
	*x = TicketTierInfo{}
	mi := &file_program_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketTierInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketTierInfo) ProtoMessage() {}

func (x *TicketTierInfo) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketTierInfo.ProtoReflect.Descriptor instead.
func (*TicketTierInfo) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{3}
}

func (x *TicketTierInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketTierInfo) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *TicketTierInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TicketTierInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketTierInfo) GetTotalStock() int32 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *TicketTierInfo) GetSoldCount() int32 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *TicketTierInfo) GetLockedCount() int32 {
	if x != nil {
		return x.LockedCount
	}
	return 0
}

func (x *TicketTierInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TicketTierInfo) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *TicketTierInfo) GetRemainStock() int32 {
	if x != nil {
		return x.RemainStock
	}
	return 0
}

type EventBrief struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PosterUrl      string                 `protobuf:"bytes,3,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	Category       *CategoryInfo          `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	VenueName      string                 `protobuf:"bytes,5,opt,name=venue_name,json=venueName,proto3" json:"venue_name,omitempty"`
	City           string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Artist         string                 `protobuf:"bytes,7,opt,name=artist,proto3" json:"artist,omitempty"`
	EventStartTime string                 `protobuf:"bytes,8,opt,name=event_start_time,json=eventStartTime,proto3" json:"event_start_time,omitempty"`
	EventEndTime   string                 `protobuf:"bytes,9,opt,name=event_end_time,json=eventEndTime,proto3" json:"event_end_time,omitempty"`
	Status         int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	MinPrice       float64                `protobuf:"fixed64,11,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	TicketType     int32                  `protobuf:"varint,12,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	IsHot          bool                   `protobuf:"varint,13,opt,name=is_hot,json=isHot,proto3" json:"is_hot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventBrief) Reset() {
	*x = EventBrief{}
	mi := &file_program_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBrief) ProtoMessage() {}

func (x *EventBrief) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBrief.ProtoReflect.Descriptor instead.
func (*EventBrief) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{4}
}

func (x *EventBrief) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventBrief) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventBrief) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *EventBrief) GetCategory() *CategoryInfo {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *EventBrief) GetVenueName() string {
	if x != nil {
		return x.VenueName
	}
	return ""
}

func (x *EventBrief) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *EventBrief) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *EventBrief) GetEventStartTime() string {
	if x != nil {
		return x.EventStartTime
	}
	return ""
}

func (x *EventBrief) GetEventEndTime() string {
	if x != nil {
		return x.EventEndTime
	}
	return ""
}

func (x *EventBrief) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EventBrief) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *EventBrief) GetTicketType() int32 {
	if x != nil {
		return x.TicketType
	}
	return 0
}

func (x *EventBrief) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

type EventDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PosterUrl      string                 `protobuf:"bytes,4,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	Category       *CategoryInfo          `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Venue          *VenueInfo             `protobuf:"bytes,6,opt,name=venue,proto3" json:"venue,omitempty"`
	City           string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Artist         string                 `protobuf:"bytes,8,opt,name=artist,proto3" json:"artist,omitempty"`
	EventStartTime string                 `protobuf:"bytes,9,opt,name=event_start_time,json=eventStartTime,proto3" json:"event_start_time,omitempty"`
	EventEndTime   string                 `protobuf:"bytes,10,opt,name=event_end_time,json=eventEndTime,proto3" json:"event_end_time,omitempty"`
	SaleStartTime  string                 `protobuf:"bytes,11,opt,name=sale_start_time,json=saleStartTime,proto3" json:"sale_start_time,omitempty"`
	SaleEndTime    string                 `protobuf:"bytes,12,opt,name=sale_end_time,json=saleEndTime,proto3" json:"sale_end_time,omitempty"`
	Status         int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	PurchaseLimit  int32                  `protobuf:"varint,14,opt,name=purchase_limit,json=purchaseLimit,proto3" json:"purchase_limit,omitempty"`
	NeedRealName   int32                  `protobuf:"varint,15,opt,name=need_real_name,json=needRealName,proto3" json:"need_real_name,omitempty"`
	TicketType     int32                  `protobuf:"varint,16,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"`
	TicketTiers    []*TicketTierInfo      `protobuf:"bytes,17,rep,name=ticket_tiers,json=ticketTiers,proto3" json:"ticket_tiers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventDetail) Reset() {
	*x = EventDetail{}
	mi := &file_program_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDetail) ProtoMessage() {}

func (x *EventDetail) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDetail.ProtoReflect.Descriptor instead.
func (*EventDetail) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{5}
}

func (x *EventDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventDetail) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *EventDetail) GetCategory() *CategoryInfo {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *EventDetail) GetVenue() *VenueInfo {
	if x != nil {
		return x.Venue
	}
	return nil
}

func (x *EventDetail) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *EventDetail) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *EventDetail) GetEventStartTime() string {
	if x != nil {
		return x.EventStartTime
	}
	return ""
}

func (x *EventDetail) GetEventEndTime() string {
	if x != nil {
		return x.EventEndTime
	}
	return ""
}

func (x *EventDetail) GetSaleStartTime() string {
	if x != nil {
		return x.SaleStartTime
	}
	return ""
}

func (x *EventDetail) GetSaleEndTime() string {
	if x != nil {
		return x.SaleEndTime
	}
	return ""
}

func (x *EventDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EventDetail) GetPurchaseLimit() int32 {
	if x != nil {
		return x.PurchaseLimit
	}
	return 0
}

func (x *EventDetail) GetNeedRealName() int32 {
	if x != nil {
		return x.NeedRealName
	}
	return 0
}

func (x *EventDetail) GetTicketType() int32 {
	if x != nil {
		return x.TicketType
	}
	return 0
}

func (x *EventDetail) GetTicketTiers() []*TicketTierInfo {
	if x != nil {
		return x.TicketTiers
	}
	return nil
}

type ListEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CategoryId    int32                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	SortBy        string                 `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventReq) Reset() {
	*x = ListEventReq{}
	mi := &file_program_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventReq) ProtoMessage() {}

func (x *ListEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventReq.ProtoReflect.Descriptor instead.
func (*ListEventReq) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{6}
}

func (x *ListEventReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEventReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventReq) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListEventReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListEventReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListEventReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ListEventReq) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type ListEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventBrief          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventResp) Reset() {
	*x = ListEventResp{}
	mi := &file_program_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventResp) ProtoMessage() {}

func (x *ListEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventResp.ProtoReflect.Descriptor instead.
func (*ListEventResp) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{7}
}

func (x *ListEventResp) GetEvents() []*EventBrief {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListEventResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEventResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetEventDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventDetailReq) Reset() {
	*x = GetEventDetailReq{}
	mi := &file_program_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventDetailReq) ProtoMessage() {}

func (x *GetEventDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventDetailReq.ProtoReflect.Descriptor instead.
func (*GetEventDetailReq) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventDetailReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetEventDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EventDetail           `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventDetailResp) Reset() {
	*x = GetEventDetailResp{}
	mi := &file_program_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventDetailResp) ProtoMessage() {}

func (x *GetEventDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventDetailResp.ProtoReflect.Descriptor instead.
func (*GetEventDetailResp) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{9}
}

func (x *GetEventDetailResp) GetEvent() *EventDetail {
	if x != nil {
		return x.Event
	}
	return nil
}

type SearchEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEventReq) Reset() {
	*x = SearchEventReq{}
	mi := &file_program_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEventReq) ProtoMessage() {}

func (x *SearchEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEventReq.ProtoReflect.Descriptor instead.
func (*SearchEventReq) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{10}
}

func (x *SearchEventReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchEventReq) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SearchEventReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SearchEventReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *SearchEventReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *SearchEventReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchEventReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventBrief          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEventResp) Reset() {
	*x = SearchEventResp{}
	mi := &file_program_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEventResp) ProtoMessage() {}

func (x *SearchEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEventResp.ProtoReflect.Descriptor instead.
func (*SearchEventResp) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{11}
}

func (x *SearchEventResp) GetEvents() []*EventBrief {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SearchEventResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchEventResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchEventResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoryReq) Reset() {
	*x = ListCategoryReq{}
	mi := &file_program_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoryReq) ProtoMessage() {}

func (x *ListCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoryReq.ProtoReflect.Descriptor instead.
func (*ListCategoryReq) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{12}
}

func (x *ListCategoryReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListCategoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryInfo        `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Cities        []*CityInfo            `protobuf:"bytes,2,rep,name=cities,proto3" json:"cities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoryResp) Reset() {
	*x = ListCategoryResp{}
	mi := &file_program_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoryResp) ProtoMessage() {}

func (x *ListCategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoryResp.ProtoReflect.Descriptor instead.
func (*ListCategoryResp) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{13}
}

func (x *ListCategoryResp) GetCategories() []*CategoryInfo {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListCategoryResp) GetCities() []*CityInfo {
	if x != nil {
		return x.Cities
	}
	return nil
}

type GetHotRecommendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotRecommendReq) Reset() {
	*x = GetHotRecommendReq{}
	mi := &file_program_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotRecommendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotRecommendReq) ProtoMessage() {}

func (x *GetHotRecommendReq) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotRecommendReq.ProtoReflect.Descriptor instead.
func (*GetHotRecommendReq) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{14}
}

func (x *GetHotRecommendReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetHotRecommendReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetHotRecommendReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetHotRecommendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventBrief          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotRecommendResp) Reset() {
	*x = GetHotRecommendResp{}
	mi := &file_program_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotRecommendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotRecommendResp) ProtoMessage() {}

func (x *GetHotRecommendResp) ProtoReflect() protoreflect.Message {
	mi := &file_program_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotRecommendResp.ProtoReflect.Descriptor instead.
func (*GetHotRecommendResp) Descriptor() ([]byte, []int) {
	return file_program_proto_rawDescGZIP(), []int{15}
}

func (x *GetHotRecommendResp) GetEvents() []*EventBrief {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_program_proto protoreflect.FileDescriptor

const file_program_proto_rawDesc = "" +
	"\n" +
	"\rprogram.proto\x12\aprogram\"}\n" +
	"\fCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\".\n" +
	"\bCityInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xbd\x01\n" +
	"\tVenueInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\x12 \n" +
	"\fseat_map_url\x18\x06 \x01(\tR\n" +
	"seatMapUrl\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\xa2\x02\n" +
	"\x0eTicketTierInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1f\n" +
	"\vtotal_stock\x18\x05 \x01(\x05R\n" +
	"totalStock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\x06 \x01(\x05R\tsoldCount\x12!\n" +
	"\flocked_count\x18\a \x01(\x05R\vlockedCount\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrder\x12!\n" +
	"\fremain_stock\x18\n" +
	" \x01(\x05R\vremainStock\"\x8c\x03\n" +
	"\n" +
	"EventBrief\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x03 \x01(\tR\tposterUrl\x121\n" +
	"\bcategory\x18\x04 \x01(\v2\x15.program.CategoryInfoR\bcategory\x12\x1d\n" +
	"\n" +
	"venue_name\x18\x05 \x01(\tR\tvenueName\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x16\n" +
	"\x06artist\x18\a \x01(\tR\x06artist\x12(\n" +
	"\x10event_start_time\x18\b \x01(\tR\x0eeventStartTime\x12$\n" +
	"\x0eevent_end_time\x18\t \x01(\tR\feventEndTime\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1b\n" +
	"\tmin_price\x18\v \x01(\x01R\bminPrice\x12\x1f\n" +
	"\vticket_type\x18\f \x01(\x05R\n" +
	"ticketType\x12\x15\n" +
	"\x06is_hot\x18\r \x01(\bR\x05isHot\"\xdb\x04\n" +
	"\vEventDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x04 \x01(\tR\tposterUrl\x121\n" +
	"\bcategory\x18\x05 \x01(\v2\x15.program.CategoryInfoR\bcategory\x12(\n" +
	"\x05venue\x18\x06 \x01(\v2\x12.program.VenueInfoR\x05venue\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x16\n" +
	"\x06artist\x18\b \x01(\tR\x06artist\x12(\n" +
	"\x10event_start_time\x18\t \x01(\tR\x0eeventStartTime\x12$\n" +
	"\x0eevent_end_time\x18\n" +
	" \x01(\tR\feventEndTime\x12&\n" +
	"\x0fsale_start_time\x18\v \x01(\tR\rsaleStartTime\x12\"\n" +
	"\rsale_end_time\x18\f \x01(\tR\vsaleEndTime\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12%\n" +
	"\x0epurchase_limit\x18\x0e \x01(\x05R\rpurchaseLimit\x12$\n" +
	"\x0eneed_real_name\x18\x0f \x01(\x05R\fneedRealName\x12\x1f\n" +
	"\vticket_type\x18\x10 \x01(\x05R\n" +
	"ticketType\x12:\n" +
	"\fticket_tiers\x18\x11 \x03(\v2\x17.program.TicketTierInfoR\vticketTiers\"\xc7\x01\n" +
	"\fListEventReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\"\x83\x01\n" +
	"\rListEventResp\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.program.EventBriefR\x06events\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\".\n" +
	"\x11GetEventDetailReq\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\"@\n" +
	"\x12GetEventDetailResp\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.program.EventDetailR\x05event\"\xca\x01\n" +
	"\x0eSearchEventReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"\x85\x01\n" +
	"\x0fSearchEventResp\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.program.EventBriefR\x06events\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\")\n" +
	"\x0fListCategoryReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"t\n" +
	"\x10ListCategoryResp\x125\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x15.program.CategoryInfoR\n" +
	"categories\x12)\n" +
	"\x06cities\x18\x02 \x03(\v2\x11.program.CityInfoR\x06cities\"W\n" +
	"\x12GetHotRecommendReq\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"B\n" +
	"\x13GetHotRecommendResp\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.program.EventBriefR\x06events2\xec\x02\n" +
	"\x0eProgramService\x12:\n" +
	"\tListEvent\x12\x15.program.ListEventReq\x1a\x16.program.ListEventResp\x12I\n" +
	"\x0eGetEventDetail\x12\x1a.program.GetEventDetailReq\x1a\x1b.program.GetEventDetailResp\x12@\n" +
	"\vSearchEvent\x12\x17.program.SearchEventReq\x1a\x18.program.SearchEventResp\x12C\n" +
	"\fListCategory\x12\x18.program.ListCategoryReq\x1a\x19.program.ListCategoryResp\x12L\n" +
	"\x0fGetHotRecommend\x12\x1b.program.GetHotRecommendReq\x1a\x1c.program.GetHotRecommendRespB\rZ\v./programpbb\x06proto3"

var (
	file_program_proto_rawDescOnce sync.Once
	file_program_proto_rawDescData []byte
)

func file_program_proto_rawDescGZIP() []byte {
	file_program_proto_rawDescOnce.Do(func() {
		file_program_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_program_proto_rawDesc), len(file_program_proto_rawDesc)))
	})
	return file_program_proto_rawDescData
}

var file_program_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_program_proto_goTypes = []any{
	(*CategoryInfo)(nil),        // 0: program.CategoryInfo
	(*CityInfo)(nil),            // 1: program.CityInfo
	(*VenueInfo)(nil),           // 2: program.VenueInfo
	(*TicketTierInfo)(nil),      // 3: program.TicketTierInfo
	(*EventBrief)(nil),          // 4: program.EventBrief
	(*EventDetail)(nil),         // 5: program.EventDetail
	(*ListEventReq)(nil),        // 6: program.ListEventReq
	(*ListEventResp)(nil),       // 7: program.ListEventResp
	(*GetEventDetailReq)(nil),   // 8: program.GetEventDetailReq
	(*GetEventDetailResp)(nil),  // 9: program.GetEventDetailResp
	(*SearchEventReq)(nil),      // 10: program.SearchEventReq
	(*SearchEventResp)(nil),     // 11: program.SearchEventResp
	(*ListCategoryReq)(nil),     // 12: program.ListCategoryReq
	(*ListCategoryResp)(nil),    // 13: program.ListCategoryResp
	(*GetHotRecommendReq)(nil),  // 14: program.GetHotRecommendReq
	(*GetHotRecommendResp)(nil), // 15: program.GetHotRecommendResp
}
var file_program_proto_depIdxs = []int32{
	0,  // 0: program.EventBrief.category:type_name -> program.CategoryInfo
	0,  // 1: program.EventDetail.category:type_name -> program.CategoryInfo
	2,  // 2: program.EventDetail.venue:type_name -> program.VenueInfo
	3,  // 3: program.EventDetail.ticket_tiers:type_name -> program.TicketTierInfo
	4,  // 4: program.ListEventResp.events:type_name -> program.EventBrief
	5,  // 5: program.GetEventDetailResp.event:type_name -> program.EventDetail
	4,  // 6: program.SearchEventResp.events:type_name -> program.EventBrief
	0,  // 7: program.ListCategoryResp.categories:type_name -> program.CategoryInfo
	1,  // 8: program.ListCategoryResp.cities:type_name -> program.CityInfo
	4,  // 9: program.GetHotRecommendResp.events:type_name -> program.EventBrief
	6,  // 10: program.ProgramService.ListEvent:input_type -> program.ListEventReq
	8,  // 11: program.ProgramService.GetEventDetail:input_type -> program.GetEventDetailReq
	10, // 12: program.ProgramService.SearchEvent:input_type -> program.SearchEventReq
	12, // 13: program.ProgramService.ListCategory:input_type -> program.ListCategoryReq
	14, // 14: program.ProgramService.GetHotRecommend:input_type -> program.GetHotRecommendReq
	7,  // 15: program.ProgramService.ListEvent:output_type -> program.ListEventResp
	9,  // 16: program.ProgramService.GetEventDetail:output_type -> program.GetEventDetailResp
	11, // 17: program.ProgramService.SearchEvent:output_type -> program.SearchEventResp
	13, // 18: program.ProgramService.ListCategory:output_type -> program.ListCategoryResp
	15, // 19: program.ProgramService.GetHotRecommend:output_type -> program.GetHotRecommendResp
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_program_proto_init() }
func file_program_proto_init() {
	if File_program_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_program_proto_rawDesc), len(file_program_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_program_proto_goTypes,
		DependencyIndexes: file_program_proto_depIdxs,
		MessageInfos:      file_program_proto_msgTypes,
	}.Build()
	File_program_proto = out.File
	file_program_proto_goTypes = nil
	file_program_proto_depIdxs = nil
}
