// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: program.proto

package programpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProgramService_ListEvent_FullMethodName       = "/program.ProgramService/ListEvent"
	ProgramService_GetEventDetail_FullMethodName  = "/program.ProgramService/GetEventDetail"
	ProgramService_SearchEvent_FullMethodName     = "/program.ProgramService/SearchEvent"
	ProgramService_ListCategory_FullMethodName    = "/program.ProgramService/ListCategory"
	ProgramService_GetHotRecommend_FullMethodName = "/program.ProgramService/GetHotRecommend"
)

// ProgramServiceClient is the client API for ProgramService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgramServiceClient interface {
	ListEvent(ctx context.Context, in *ListEventReq, opts ...grpc.CallOption) (*ListEventResp, error)
	GetEventDetail(ctx context.Context, in *GetEventDetailReq, opts ...grpc.CallOption) (*GetEventDetailResp, error)
	SearchEvent(ctx context.Context, in *SearchEventReq, opts ...grpc.CallOption) (*SearchEventResp, error)
	ListCategory(ctx context.Context, in *ListCategoryReq, opts ...grpc.CallOption) (*ListCategoryResp, error)
	GetHotRecommend(ctx context.Context, in *GetHotRecommendReq, opts ...grpc.CallOption) (*GetHotRecommendResp, error)
}

type programServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProgramServiceClient(cc grpc.ClientConnInterface) ProgramServiceClient {
	return &programServiceClient{cc}
}

func (c *programServiceClient) ListEvent(ctx context.Context, in *ListEventReq, opts ...grpc.CallOption) (*ListEventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventResp)
	err := c.cc.Invoke(ctx, ProgramService_ListEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) GetEventDetail(ctx context.Context, in *GetEventDetailReq, opts ...grpc.CallOption) (*GetEventDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventDetailResp)
	err := c.cc.Invoke(ctx, ProgramService_GetEventDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) SearchEvent(ctx context.Context, in *SearchEventReq, opts ...grpc.CallOption) (*SearchEventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEventResp)
	err := c.cc.Invoke(ctx, ProgramService_SearchEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) ListCategory(ctx context.Context, in *ListCategoryReq, opts ...grpc.CallOption) (*ListCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoryResp)
	err := c.cc.Invoke(ctx, ProgramService_ListCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) GetHotRecommend(ctx context.Context, in *GetHotRecommendReq, opts ...grpc.CallOption) (*GetHotRecommendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotRecommendResp)
	err := c.cc.Invoke(ctx, ProgramService_GetHotRecommend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgramServiceServer is the server API for ProgramService service.
// All implementations must embed UnimplementedProgramServiceServer
// for forward compatibility.
type ProgramServiceServer interface {
	ListEvent(context.Context, *ListEventReq) (*ListEventResp, error)
	GetEventDetail(context.Context, *GetEventDetailReq) (*GetEventDetailResp, error)
	SearchEvent(context.Context, *SearchEventReq) (*SearchEventResp, error)
	ListCategory(context.Context, *ListCategoryReq) (*ListCategoryResp, error)
	GetHotRecommend(context.Context, *GetHotRecommendReq) (*GetHotRecommendResp, error)
	mustEmbedUnimplementedProgramServiceServer()
}

// UnimplementedProgramServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgramServiceServer struct{}

func (UnimplementedProgramServiceServer) ListEvent(context.Context, *ListEventReq) (*ListEventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvent not implemented")
}
func (UnimplementedProgramServiceServer) GetEventDetail(context.Context, *GetEventDetailReq) (*GetEventDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventDetail not implemented")
}
func (UnimplementedProgramServiceServer) SearchEvent(context.Context, *SearchEventReq) (*SearchEventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchEvent not implemented")
}
func (UnimplementedProgramServiceServer) ListCategory(context.Context, *ListCategoryReq) (*ListCategoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategory not implemented")
}
func (UnimplementedProgramServiceServer) GetHotRecommend(context.Context, *GetHotRecommendReq) (*GetHotRecommendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotRecommend not implemented")
}
func (UnimplementedProgramServiceServer) mustEmbedUnimplementedProgramServiceServer() {}
func (UnimplementedProgramServiceServer) testEmbeddedByValue()                        {}

// UnsafeProgramServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgramServiceServer will
// result in compilation errors.
type UnsafeProgramServiceServer interface {
	mustEmbedUnimplementedProgramServiceServer()
}

func RegisterProgramServiceServer(s grpc.ServiceRegistrar, srv ProgramServiceServer) {
	// If the following call panics, it indicates UnimplementedProgramServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProgramService_ServiceDesc, srv)
}

func _ProgramService_ListEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).ListEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_ListEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).ListEvent(ctx, req.(*ListEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_GetEventDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).GetEventDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_GetEventDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).GetEventDetail(ctx, req.(*GetEventDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_SearchEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).SearchEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_SearchEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).SearchEvent(ctx, req.(*SearchEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_ListCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).ListCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_ListCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).ListCategory(ctx, req.(*ListCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_GetHotRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotRecommendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).GetHotRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_GetHotRecommend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).GetHotRecommend(ctx, req.(*GetHotRecommendReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProgramService_ServiceDesc is the grpc.ServiceDesc for ProgramService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgramService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "program.ProgramService",
	HandlerType: (*ProgramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEvent",
			Handler:    _ProgramService_ListEvent_Handler,
		},
		{
			MethodName: "GetEventDetail",
			Handler:    _ProgramService_GetEventDetail_Handler,
		},
		{
			MethodName: "SearchEvent",
			Handler:    _ProgramService_SearchEvent_Handler,
		},
		{
			MethodName: "ListCategory",
			Handler:    _ProgramService_ListCategory_Handler,
		},
		{
			MethodName: "GetHotRecommend",
			Handler:    _ProgramService_GetHotRecommend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "program.proto",
}
