// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: app/rpc/payment/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentNo     string                 `protobuf:"bytes,2,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	PayMethod     int32                  `protobuf:"varint,3,opt,name=pay_method,json=payMethod,proto3" json:"pay_method,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	TradeNo       string                 `protobuf:"bytes,6,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	PaidAt        string                 `protobuf:"bytes,7,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CallbackData  string                 `protobuf:"bytes,10,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentInfo) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *PaymentInfo) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

func (x *PaymentInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PaymentInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *PaymentInfo) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *PaymentInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PaymentInfo) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

type RefundInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RefundNo      string                 `protobuf:"bytes,2,opt,name=refund_no,json=refundNo,proto3" json:"refund_no,omitempty"`
	RefundAmount  float64                `protobuf:"fixed64,3,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	RejectReason  string                 `protobuf:"bytes,6,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	TradeNo       string                 `protobuf:"bytes,7,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RefundedAt    string                 `protobuf:"bytes,10,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundInfo) Reset() {
	*x = RefundInfo{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfo) ProtoMessage() {}

func (x *RefundInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfo.ProtoReflect.Descriptor instead.
func (*RefundInfo) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *RefundInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RefundInfo) GetRefundNo() string {
	if x != nil {
		return x.RefundNo
	}
	return ""
}

func (x *RefundInfo) GetRefundAmount() float64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *RefundInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RefundInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundInfo) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *RefundInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *RefundInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RefundInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RefundInfo) GetRefundedAt() string {
	if x != nil {
		return x.RefundedAt
	}
	return ""
}

type PayOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PayMethod     int32                  `protobuf:"varint,3,opt,name=pay_method,json=payMethod,proto3" json:"pay_method,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,5,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,6,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	Subject       string                 `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderReq) Reset() {
	*x = PayOrderReq{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderReq) ProtoMessage() {}

func (x *PayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderReq.ProtoReflect.Descriptor instead.
func (*PayOrderReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PayOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayOrderReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PayOrderReq) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

func (x *PayOrderReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PayOrderReq) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *PayOrderReq) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *PayOrderReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type PayOrderResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PayForm           string                 `protobuf:"bytes,2,opt,name=pay_form,json=payForm,proto3" json:"pay_form,omitempty"`
	Payment           *PaymentInfo           `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	OrderStatus       int32                  `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaidAt            string                 `protobuf:"bytes,5,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CheckoutUrl       string                 `protobuf:"bytes,6,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	CheckoutSessionId string                 `protobuf:"bytes,7,opt,name=checkout_session_id,json=checkoutSessionId,proto3" json:"checkout_session_id,omitempty"`
	SessionExpiresAt  string                 `protobuf:"bytes,8,opt,name=session_expires_at,json=sessionExpiresAt,proto3" json:"session_expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PayOrderResp) Reset() {
	*x = PayOrderResp{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderResp) ProtoMessage() {}

func (x *PayOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderResp.ProtoReflect.Descriptor instead.
func (*PayOrderResp) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PayOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PayOrderResp) GetPayForm() string {
	if x != nil {
		return x.PayForm
	}
	return ""
}

func (x *PayOrderResp) GetPayment() *PaymentInfo {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *PayOrderResp) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *PayOrderResp) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *PayOrderResp) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *PayOrderResp) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

func (x *PayOrderResp) GetSessionExpiresAt() string {
	if x != nil {
		return x.SessionExpiresAt
	}
	return ""
}

type NotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RawBody       []byte                 `protobuf:"bytes,3,opt,name=raw_body,json=rawBody,proto3" json:"raw_body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyReq) Reset() {
	*x = NotifyReq{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq) ProtoMessage() {}

func (x *NotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq.ProtoReflect.Descriptor instead.
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *NotifyReq) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *NotifyReq) GetRawBody() []byte {
	if x != nil {
		return x.RawBody
	}
	return nil
}

func (x *NotifyReq) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *NotifyReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type NotifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AckText       string                 `protobuf:"bytes,2,opt,name=ack_text,json=ackText,proto3" json:"ack_text,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Payment       *PaymentInfo           `protobuf:"bytes,4,opt,name=payment,proto3" json:"payment,omitempty"`
	OrderStatus   int32                  `protobuf:"varint,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaidAt        string                 `protobuf:"bytes,6,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResp) Reset() {
	*x = NotifyResp{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResp) ProtoMessage() {}

func (x *NotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResp.ProtoReflect.Descriptor instead.
func (*NotifyResp) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotifyResp) GetAckText() string {
	if x != nil {
		return x.AckText
	}
	return ""
}

func (x *NotifyResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *NotifyResp) GetPayment() *PaymentInfo {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *NotifyResp) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *NotifyResp) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

type TradeCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PaymentNo     string                 `protobuf:"bytes,3,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeCheckReq) Reset() {
	*x = TradeCheckReq{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeCheckReq) ProtoMessage() {}

func (x *TradeCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeCheckReq.ProtoReflect.Descriptor instead.
func (*TradeCheckReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *TradeCheckReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TradeCheckReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *TradeCheckReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *TradeCheckReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type TradeCheckResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Paid              bool                   `protobuf:"varint,2,opt,name=paid,proto3" json:"paid,omitempty"`
	Payment           *PaymentInfo           `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	OrderStatus       int32                  `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaidAt            string                 `protobuf:"bytes,5,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CheckoutSessionId string                 `protobuf:"bytes,6,opt,name=checkout_session_id,json=checkoutSessionId,proto3" json:"checkout_session_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TradeCheckResp) Reset() {
	*x = TradeCheckResp{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeCheckResp) ProtoMessage() {}

func (x *TradeCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeCheckResp.ProtoReflect.Descriptor instead.
func (*TradeCheckResp) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *TradeCheckResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TradeCheckResp) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *TradeCheckResp) GetPayment() *PaymentInfo {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *TradeCheckResp) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *TradeCheckResp) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *TradeCheckResp) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

type RefundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	RefundAmount  float64                `protobuf:"fixed64,5,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundReq) Reset() {
	*x = RefundReq{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundReq) ProtoMessage() {}

func (x *RefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundReq.ProtoReflect.Descriptor instead.
func (*RefundReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{8}
}

func (x *RefundReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RefundReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *RefundReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RefundReq) GetRefundAmount() float64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

type RefundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Refund        *RefundInfo            `protobuf:"bytes,3,opt,name=refund,proto3" json:"refund,omitempty"`
	OrderStatus   int32                  `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	ShouldRelease bool                   `protobuf:"varint,5,opt,name=should_release,json=shouldRelease,proto3" json:"should_release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResp) Reset() {
	*x = RefundResp{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResp) ProtoMessage() {}

func (x *RefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResp.ProtoReflect.Descriptor instead.
func (*RefundResp) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{9}
}

func (x *RefundResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefundResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *RefundResp) GetRefund() *RefundInfo {
	if x != nil {
		return x.Refund
	}
	return nil
}

func (x *RefundResp) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *RefundResp) GetShouldRelease() bool {
	if x != nil {
		return x.ShouldRelease
	}
	return false
}

type DetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailReq) Reset() {
	*x = DetailReq{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailReq) ProtoMessage() {}

func (x *DetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailReq.ProtoReflect.Descriptor instead.
func (*DetailReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{10}
}

func (x *DetailReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DetailReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type DetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentInfo           `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Refund        *RefundInfo            `protobuf:"bytes,2,opt,name=refund,proto3" json:"refund,omitempty"`
	OrderStatus   int32                  `protobuf:"varint,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaidAt        string                 `protobuf:"bytes,4,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailResp) Reset() {
	*x = DetailResp{}
	mi := &file_app_rpc_payment_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailResp) ProtoMessage() {}

func (x *DetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_payment_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailResp.ProtoReflect.Descriptor instead.
func (*DetailResp) Descriptor() ([]byte, []int) {
	return file_app_rpc_payment_payment_proto_rawDescGZIP(), []int{11}
}

func (x *DetailResp) GetPayment() *PaymentInfo {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *DetailResp) GetRefund() *RefundInfo {
	if x != nil {
		return x.Refund
	}
	return nil
}

func (x *DetailResp) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *DetailResp) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

var File_app_rpc_payment_payment_proto protoreflect.FileDescriptor

const file_app_rpc_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x1dapp/rpc/payment/payment.proto\x12\apayment\"\xa2\x02\n" +
	"\vPaymentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x02 \x01(\tR\tpaymentNo\x12\x1d\n" +
	"\n" +
	"pay_method\x18\x03 \x01(\x05R\tpayMethod\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x19\n" +
	"\btrade_no\x18\x06 \x01(\tR\atradeNo\x12\x17\n" +
	"\apaid_at\x18\a \x01(\tR\x06paidAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12#\n" +
	"\rcallback_data\x18\n" +
	" \x01(\tR\fcallbackData\"\xad\x02\n" +
	"\n" +
	"RefundInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\trefund_no\x18\x02 \x01(\tR\brefundNo\x12#\n" +
	"\rrefund_amount\x18\x03 \x01(\x01R\frefundAmount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12#\n" +
	"\rreject_reason\x18\x06 \x01(\tR\frejectReason\x12\x19\n" +
	"\btrade_no\x18\a \x01(\tR\atradeNo\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vrefunded_at\x18\n" +
	" \x01(\tR\n" +
	"refundedAt\"\xd2\x01\n" +
	"\vPayOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"pay_method\x18\x03 \x01(\x05R\tpayMethod\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x05 \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\x06 \x01(\tR\treturnUrl\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\"\xb0\x02\n" +
	"\fPayOrderResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bpay_form\x18\x02 \x01(\tR\apayForm\x12.\n" +
	"\apayment\x18\x03 \x01(\v2\x14.payment.PaymentInfoR\apayment\x12!\n" +
	"\forder_status\x18\x04 \x01(\x05R\vorderStatus\x12\x17\n" +
	"\apaid_at\x18\x05 \x01(\tR\x06paidAt\x12!\n" +
	"\fcheckout_url\x18\x06 \x01(\tR\vcheckoutUrl\x12.\n" +
	"\x13checkout_session_id\x18\a \x01(\tR\x11checkoutSessionId\x12,\n" +
	"\x12session_expires_at\x18\b \x01(\tR\x10sessionExpiresAt\"\xc8\x02\n" +
	"\tNotifyReq\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x126\n" +
	"\x06params\x18\x02 \x03(\v2\x1e.payment.NotifyReq.ParamsEntryR\x06params\x12\x19\n" +
	"\braw_body\x18\x03 \x01(\fR\arawBody\x129\n" +
	"\aheaders\x18\x04 \x03(\v2\x1f.payment.NotifyReq.HeadersEntryR\aheaders\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x01\n" +
	"\n" +
	"NotifyResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\back_text\x18\x02 \x01(\tR\aackText\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12.\n" +
	"\apayment\x18\x04 \x01(\v2\x14.payment.PaymentInfoR\apayment\x12!\n" +
	"\forder_status\x18\x05 \x01(\x05R\vorderStatus\x12\x17\n" +
	"\apaid_at\x18\x06 \x01(\tR\x06paidAt\"|\n" +
	"\rTradeCheckReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x03 \x01(\tR\tpaymentNo\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\"\xda\x01\n" +
	"\x0eTradeCheckResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04paid\x18\x02 \x01(\bR\x04paid\x12.\n" +
	"\apayment\x18\x03 \x01(\v2\x14.payment.PaymentInfoR\apayment\x12!\n" +
	"\forder_status\x18\x04 \x01(\x05R\vorderStatus\x12\x17\n" +
	"\apaid_at\x18\x05 \x01(\tR\x06paidAt\x12.\n" +
	"\x13checkout_session_id\x18\x06 \x01(\tR\x11checkoutSessionId\"\x96\x01\n" +
	"\tRefundReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12#\n" +
	"\rrefund_amount\x18\x05 \x01(\x01R\frefundAmount\"\xb8\x01\n" +
	"\n" +
	"RefundResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12+\n" +
	"\x06refund\x18\x03 \x01(\v2\x13.payment.RefundInfoR\x06refund\x12!\n" +
	"\forder_status\x18\x04 \x01(\x05R\vorderStatus\x12%\n" +
	"\x0eshould_release\x18\x05 \x01(\bR\rshouldRelease\"?\n" +
	"\tDetailReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\"\xa5\x01\n" +
	"\n" +
	"DetailResp\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payment.PaymentInfoR\apayment\x12+\n" +
	"\x06refund\x18\x02 \x01(\v2\x13.payment.RefundInfoR\x06refund\x12!\n" +
	"\forder_status\x18\x03 \x01(\x05R\vorderStatus\x12\x17\n" +
	"\apaid_at\x18\x04 \x01(\tR\x06paidAt2\xa1\x02\n" +
	"\x0ePaymentService\x127\n" +
	"\bPayOrder\x12\x14.payment.PayOrderReq\x1a\x15.payment.PayOrderResp\x121\n" +
	"\x06Notify\x12\x12.payment.NotifyReq\x1a\x13.payment.NotifyResp\x12=\n" +
	"\n" +
	"TradeCheck\x12\x16.payment.TradeCheckReq\x1a\x17.payment.TradeCheckResp\x121\n" +
	"\x06Refund\x12\x12.payment.RefundReq\x1a\x13.payment.RefundResp\x121\n" +
	"\x06Detail\x12\x12.payment.DetailReq\x1a\x13.payment.DetailRespB\x1cZ\x1aserver/paymentpb;paymentpbb\x06proto3"

var (
	file_app_rpc_payment_payment_proto_rawDescOnce sync.Once
	file_app_rpc_payment_payment_proto_rawDescData []byte
)

func file_app_rpc_payment_payment_proto_rawDescGZIP() []byte {
	file_app_rpc_payment_payment_proto_rawDescOnce.Do(func() {
		file_app_rpc_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_rpc_payment_payment_proto_rawDesc), len(file_app_rpc_payment_payment_proto_rawDesc)))
	})
	return file_app_rpc_payment_payment_proto_rawDescData
}

var file_app_rpc_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_app_rpc_payment_payment_proto_goTypes = []any{
	(*PaymentInfo)(nil),    // 0: payment.PaymentInfo
	(*RefundInfo)(nil),     // 1: payment.RefundInfo
	(*PayOrderReq)(nil),    // 2: payment.PayOrderReq
	(*PayOrderResp)(nil),   // 3: payment.PayOrderResp
	(*NotifyReq)(nil),      // 4: payment.NotifyReq
	(*NotifyResp)(nil),     // 5: payment.NotifyResp
	(*TradeCheckReq)(nil),  // 6: payment.TradeCheckReq
	(*TradeCheckResp)(nil), // 7: payment.TradeCheckResp
	(*RefundReq)(nil),      // 8: payment.RefundReq
	(*RefundResp)(nil),     // 9: payment.RefundResp
	(*DetailReq)(nil),      // 10: payment.DetailReq
	(*DetailResp)(nil),     // 11: payment.DetailResp
	nil,                    // 12: payment.NotifyReq.ParamsEntry
	nil,                    // 13: payment.NotifyReq.HeadersEntry
}
var file_app_rpc_payment_payment_proto_depIdxs = []int32{
	0,  // 0: payment.PayOrderResp.payment:type_name -> payment.PaymentInfo
	12, // 1: payment.NotifyReq.params:type_name -> payment.NotifyReq.ParamsEntry
	13, // 2: payment.NotifyReq.headers:type_name -> payment.NotifyReq.HeadersEntry
	0,  // 3: payment.NotifyResp.payment:type_name -> payment.PaymentInfo
	0,  // 4: payment.TradeCheckResp.payment:type_name -> payment.PaymentInfo
	1,  // 5: payment.RefundResp.refund:type_name -> payment.RefundInfo
	0,  // 6: payment.DetailResp.payment:type_name -> payment.PaymentInfo
	1,  // 7: payment.DetailResp.refund:type_name -> payment.RefundInfo
	2,  // 8: payment.PaymentService.PayOrder:input_type -> payment.PayOrderReq
	4,  // 9: payment.PaymentService.Notify:input_type -> payment.NotifyReq
	6,  // 10: payment.PaymentService.TradeCheck:input_type -> payment.TradeCheckReq
	8,  // 11: payment.PaymentService.Refund:input_type -> payment.RefundReq
	10, // 12: payment.PaymentService.Detail:input_type -> payment.DetailReq
	3,  // 13: payment.PaymentService.PayOrder:output_type -> payment.PayOrderResp
	5,  // 14: payment.PaymentService.Notify:output_type -> payment.NotifyResp
	7,  // 15: payment.PaymentService.TradeCheck:output_type -> payment.TradeCheckResp
	9,  // 16: payment.PaymentService.Refund:output_type -> payment.RefundResp
	11, // 17: payment.PaymentService.Detail:output_type -> payment.DetailResp
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_app_rpc_payment_payment_proto_init() }
func file_app_rpc_payment_payment_proto_init() {
	if File_app_rpc_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_rpc_payment_payment_proto_rawDesc), len(file_app_rpc_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_rpc_payment_payment_proto_goTypes,
		DependencyIndexes: file_app_rpc_payment_payment_proto_depIdxs,
		MessageInfos:      file_app_rpc_payment_payment_proto_msgTypes,
	}.Build()
	File_app_rpc_payment_payment_proto = out.File
	file_app_rpc_payment_payment_proto_goTypes = nil
	file_app_rpc_payment_payment_proto_depIdxs = nil
}
