// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userservice

import (
	"context"

	"server/app/rpc/user/userpb/userpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddressInfo               = userpb.AddressInfo
	ChangePasswordReq         = userpb.ChangePasswordReq
	ChangePasswordResp        = userpb.ChangePasswordResp
	CreateAddressReq          = userpb.CreateAddressReq
	CreateAddressResp         = userpb.CreateAddressResp
	CreateTicketBuyerReq      = userpb.CreateTicketBuyerReq
	CreateTicketBuyerResp     = userpb.CreateTicketBuyerResp
	DeleteAddressReq          = userpb.DeleteAddressReq
	DeleteAddressResp         = userpb.DeleteAddressResp
	DeleteTicketBuyerReq      = userpb.DeleteTicketBuyerReq
	DeleteTicketBuyerResp     = userpb.DeleteTicketBuyerResp
	GetUserInfoReq            = userpb.GetUserInfoReq
	GetUserInfoResp           = userpb.GetUserInfoResp
	ListAddressReq            = userpb.ListAddressReq
	ListAddressResp           = userpb.ListAddressResp
	ListTicketBuyerReq        = userpb.ListTicketBuyerReq
	ListTicketBuyerResp       = userpb.ListTicketBuyerResp
	LoginReq                  = userpb.LoginReq
	LoginResp                 = userpb.LoginResp
	LogoutReq                 = userpb.LogoutReq
	LogoutResp                = userpb.LogoutResp
	RefreshTokenReq           = userpb.RefreshTokenReq
	RefreshTokenResp          = userpb.RefreshTokenResp
	RegisterReq               = userpb.RegisterReq
	RegisterResp              = userpb.RegisterResp
	SetDefaultAddressReq      = userpb.SetDefaultAddressReq
	SetDefaultAddressResp     = userpb.SetDefaultAddressResp
	SetDefaultTicketBuyerReq  = userpb.SetDefaultTicketBuyerReq
	SetDefaultTicketBuyerResp = userpb.SetDefaultTicketBuyerResp
	TicketBuyerInfo           = userpb.TicketBuyerInfo
	UpdateAddressReq          = userpb.UpdateAddressReq
	UpdateAddressResp         = userpb.UpdateAddressResp
	UpdateTicketBuyerReq      = userpb.UpdateTicketBuyerReq
	UpdateTicketBuyerResp     = userpb.UpdateTicketBuyerResp
	UpdateUserInfoReq         = userpb.UpdateUserInfoReq
	UpdateUserInfoResp        = userpb.UpdateUserInfoResp
	UserInfo                  = userpb.UserInfo
	ValidateTokenReq          = userpb.ValidateTokenReq
	ValidateTokenResp         = userpb.ValidateTokenResp
	VerifyRealNameReq         = userpb.VerifyRealNameReq
	VerifyRealNameResp        = userpb.VerifyRealNameResp

	UserService interface {
		// --- 认证相关 ---
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
		// --- 用户信息 ---
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error)
		ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*ChangePasswordResp, error)
		VerifyRealName(ctx context.Context, in *VerifyRealNameReq, opts ...grpc.CallOption) (*VerifyRealNameResp, error)
		// --- 收货地址 ---
		CreateAddress(ctx context.Context, in *CreateAddressReq, opts ...grpc.CallOption) (*CreateAddressResp, error)
		UpdateAddress(ctx context.Context, in *UpdateAddressReq, opts ...grpc.CallOption) (*UpdateAddressResp, error)
		DeleteAddress(ctx context.Context, in *DeleteAddressReq, opts ...grpc.CallOption) (*DeleteAddressResp, error)
		ListAddress(ctx context.Context, in *ListAddressReq, opts ...grpc.CallOption) (*ListAddressResp, error)
		SetDefaultAddress(ctx context.Context, in *SetDefaultAddressReq, opts ...grpc.CallOption) (*SetDefaultAddressResp, error)
		// --- 常用购票人 ---
		CreateTicketBuyer(ctx context.Context, in *CreateTicketBuyerReq, opts ...grpc.CallOption) (*CreateTicketBuyerResp, error)
		UpdateTicketBuyer(ctx context.Context, in *UpdateTicketBuyerReq, opts ...grpc.CallOption) (*UpdateTicketBuyerResp, error)
		DeleteTicketBuyer(ctx context.Context, in *DeleteTicketBuyerReq, opts ...grpc.CallOption) (*DeleteTicketBuyerResp, error)
		ListTicketBuyer(ctx context.Context, in *ListTicketBuyerReq, opts ...grpc.CallOption) (*ListTicketBuyerResp, error)
		SetDefaultTicketBuyer(ctx context.Context, in *SetDefaultTicketBuyerReq, opts ...grpc.CallOption) (*SetDefaultTicketBuyerResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// --- 认证相关 ---
func (m *defaultUserService) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserService) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultUserService) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultUserService) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

// --- 用户信息 ---
func (m *defaultUserService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*ChangePasswordResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

func (m *defaultUserService) VerifyRealName(ctx context.Context, in *VerifyRealNameReq, opts ...grpc.CallOption) (*VerifyRealNameResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.VerifyRealName(ctx, in, opts...)
}

// --- 收货地址 ---
func (m *defaultUserService) CreateAddress(ctx context.Context, in *CreateAddressReq, opts ...grpc.CallOption) (*CreateAddressResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.CreateAddress(ctx, in, opts...)
}

func (m *defaultUserService) UpdateAddress(ctx context.Context, in *UpdateAddressReq, opts ...grpc.CallOption) (*UpdateAddressResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateAddress(ctx, in, opts...)
}

func (m *defaultUserService) DeleteAddress(ctx context.Context, in *DeleteAddressReq, opts ...grpc.CallOption) (*DeleteAddressResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.DeleteAddress(ctx, in, opts...)
}

func (m *defaultUserService) ListAddress(ctx context.Context, in *ListAddressReq, opts ...grpc.CallOption) (*ListAddressResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.ListAddress(ctx, in, opts...)
}

func (m *defaultUserService) SetDefaultAddress(ctx context.Context, in *SetDefaultAddressReq, opts ...grpc.CallOption) (*SetDefaultAddressResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.SetDefaultAddress(ctx, in, opts...)
}

// --- 常用购票人 ---
func (m *defaultUserService) CreateTicketBuyer(ctx context.Context, in *CreateTicketBuyerReq, opts ...grpc.CallOption) (*CreateTicketBuyerResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.CreateTicketBuyer(ctx, in, opts...)
}

func (m *defaultUserService) UpdateTicketBuyer(ctx context.Context, in *UpdateTicketBuyerReq, opts ...grpc.CallOption) (*UpdateTicketBuyerResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateTicketBuyer(ctx, in, opts...)
}

func (m *defaultUserService) DeleteTicketBuyer(ctx context.Context, in *DeleteTicketBuyerReq, opts ...grpc.CallOption) (*DeleteTicketBuyerResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.DeleteTicketBuyer(ctx, in, opts...)
}

func (m *defaultUserService) ListTicketBuyer(ctx context.Context, in *ListTicketBuyerReq, opts ...grpc.CallOption) (*ListTicketBuyerResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.ListTicketBuyer(ctx, in, opts...)
}

func (m *defaultUserService) SetDefaultTicketBuyer(ctx context.Context, in *SetDefaultTicketBuyerReq, opts ...grpc.CallOption) (*SetDefaultTicketBuyerResp, error) {
	client := userpb.NewUserServiceClient(m.cli.Conn())
	return client.SetDefaultTicketBuyer(ctx, in, opts...)
}
